using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using BUS;
using DevExpress.XtraTreeList;
using DevExpress.XtraTreeList.Columns;
using DevExpress.XtraTreeList.Nodes;

namespace QLSanPhamDienTu
{
    public partial class frmQLNhanVienPhanQuyen : Form
    {
        public frmQLNhanVienPhanQuyen()
        {
            InitializeComponent();
            //CreateNodes(treeViewNguoiDung);

            // This line of code is generated by Data Source Configuration Wizard
        }

        private void CreateNodes(TreeList tl)
        {
            tl.BeginUnboundLoad();
            // Create a root node .
            TreeListNode parentForRootNodes = null;
            TreeListNode rootNode = tl.AppendNode(
                new object[] { "Alfreds Futterkiste", "Germany, Obere Str. 57", "030-0074321" },
                parentForRootNodes);
            // Create a child of the rootNode
            tl.AppendNode(new object[] { "Suyama, Michael", "Obere Str. 55", "030-0074263" }, rootNode);
            // Creating more nodes
            // ...
            tl.EndUnboundLoad();
        }

        private void frmQLNhanVienPhanQuyen_Load(object sender, EventArgs e)
        {
            NguoiDungBUS.Instance.loadNhomNguoiDung(treeViewNguoiDung);
        }

        private void panelControl1_Paint(object sender, PaintEventArgs e)
        {

        }
    }
}
