// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 16.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedU_QLSanPhamDienTu
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using DevExpress.CodedUIExtension.DXTestControls.v19_2;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Thieu ten san pham
        /// </summary>
        public void RecordedMethod1_ThemThatBai1()
        {
            #region Variable Declarations
            WinWindow uITxtXuatSuWindow = this.UIThôngtinsảnphẩmWindow.UIThôngtinsảnphẩmGroup.UITxtXuatSuWindow;
            WinEdit uITxtXuatSuEdit = this.UIThôngtinsảnphẩmWindow.UITxtXuatSuWindow.UITxtXuatSuEdit;
            WinWindow uIItem0Window = this.UIThôngtinsảnphẩmWindow.UINumericUpDownSpinner.UIItem0Window;
            WinEdit uINumericUpDownEdit = this.UIThôngtinsảnphẩmWindow.UINumericUpDownSpinner.UINumericUpDownEdit;
            WinWindow uITxtDonGiaWindow = this.UIThôngtinsảnphẩmWindow.UIThôngtinsảnphẩmGroup.UITxtDonGiaWindow;
            WinEdit uITxtDonGiaEdit = this.UIThôngtinsảnphẩmWindow.UITxtDonGiaWindow.UITxtDonGiaEdit;
            WinWindow uITxtHinhMHWindow = this.UIThôngtinsảnphẩmWindow.UIThôngtinsảnphẩmGroup.UITxtHinhMHWindow;
            WinEdit uITxtHinhMHEdit = this.UIThôngtinsảnphẩmWindow.UITxtHinhMHWindow.UITxtHinhMHEdit;
            WinWindow uITxtGiamGiaWindow = this.UIThôngtinsảnphẩmWindow.UIThôngtinsảnphẩmGroup.UITxtGiamGiaWindow;
            WinEdit uITxtGiamGiaEdit = this.UIThôngtinsảnphẩmWindow.UITxtGiamGiaWindow.UITxtGiamGiaEdit;
            WinWindow uITxtDSHinhWindow = this.UIThôngtinsảnphẩmWindow.UIThôngtinsảnphẩmGroup.UITxtDSHinhWindow;
            WinEdit uITxtDSHinhEdit = this.UIThôngtinsảnphẩmWindow.UITxtDSHinhWindow.UITxtDSHinhEdit;
            WinWindow uITxtKhuyenMaiDiKemWindow = this.UIThôngtinsảnphẩmWindow.UIThôngtinsảnphẩmGroup.UITxtKhuyenMaiDiKemWindow;
            WinEdit uITxtKhuyenMaiDiKemEdit = this.UIThôngtinsảnphẩmWindow.UITxtKhuyenMaiDiKemWindow.UITxtKhuyenMaiDiKemEdit;
            WinWindow uITxtThongTinChiTietWindow = this.UIThôngtinsảnphẩmWindow.UIThôngtinsảnphẩmGroup.UITxtThongTinChiTietWindow;
            WinWindow uITxtManHinhWindow = this.UIThôngtinmôtảchitiếtsWindow.UIThôngtinmôtảsảnphẩmGroup.UITxtManHinhWindow;
            WinGroup uIThôngtinmôtảsảnphẩmGroup = this.UIThôngtinmôtảchitiếtsWindow.UIThôngtinmôtảsảnphẩmWindow.UIThôngtinmôtảsảnphẩmGroup;
            WinEdit uITxtManHinhEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtManHinhWindow.UITxtManHinhEdit;
            WinWindow uITxtCameraSauWindow = this.UIThôngtinmôtảchitiếtsWindow.UIThôngtinmôtảsảnphẩmGroup.UITxtCameraSauWindow;
            WinEdit uITxtCameraSauEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtCameraSauWindow.UITxtCameraSauEdit;
            WinWindow uITxtCameraSelfiWindow = this.UIThôngtinmôtảchitiếtsWindow.UIThôngtinmôtảsảnphẩmGroup.UITxtCameraSelfiWindow;
            WinEdit uITxtCameraSelfiEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtCameraSelfiWindow.UITxtCameraSelfiEdit;
            WinWindow uIItem0Window1 = this.UIThôngtinmôtảchitiếtsWindow.UINumericUpDownSpinner.UIItem0Window;
            WinEdit uINumericUpDownEdit1 = this.UIThôngtinmôtảchitiếtsWindow.UINumericUpDownSpinner.UINumericUpDownEdit;
            WinWindow uIItem0Window2 = this.UIThôngtinmôtảchitiếtsWindow.UIGBSpinner.UIItem0Window;
            WinEdit uIGBEdit = this.UIThôngtinmôtảchitiếtsWindow.UIGBSpinner.UIGBEdit;
            WinWindow uITxtCPUWindow = this.UIThôngtinmôtảchitiếtsWindow.UIThôngtinmôtảsảnphẩmGroup.UITxtCPUWindow;
            WinEdit uITxtCPUEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtCPUWindow.UITxtCPUEdit;
            WinWindow uITxtGPUWindow = this.UIThôngtinmôtảchitiếtsWindow.UIThôngtinmôtảsảnphẩmGroup.UITxtGPUWindow;
            WinEdit uITxtGPUEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtGPUWindow.UITxtGPUEdit;
            WinWindow uITxtDungLuongPinWindow = this.UIThôngtinmôtảchitiếtsWindow.UIThôngtinmôtảsảnphẩmGroup.UITxtDungLuongPinWindow;
            WinEdit uITxtDungLuongPinEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtDungLuongPinWindow.UITxtDungLuongPinEdit;
            WinWindow uITxtTheSimWindow = this.UIThôngtinmôtảchitiếtsWindow.UIThôngtinmôtảsảnphẩmGroup.UITxtTheSimWindow;
            WinEdit uITxtTheSimEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtTheSimWindow.UITxtTheSimEdit;
            WinWindow uITxtHeDieuHanhWindow = this.UIThôngtinmôtảchitiếtsWindow.UIThôngtinmôtảsảnphẩmGroup.UITxtHeDieuHanhWindow;
            WinEdit uITxtHeDieuHanhEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtHeDieuHanhWindow.UITxtHeDieuHanhEdit;
            DXButton uIHoàntấtButton = this.UIThôngtinmôtảchitiếtsWindow.UIHoàntấtButton;
            DXButton uIThêmmớiButton = this.UIThôngtinsảnphẩmWindow.UIThêmmớiButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            #endregion

            // Click 'txtXuatSu' window
            Mouse.Click(uITxtXuatSuWindow, new Point(244, 98));

            // Type 'Trung Quốc' in 'txtXuatSu' text box
            uITxtXuatSuEdit.Text = this.RecordedMethod1_ThemThatBai1Params.UITxtXuatSuEditText;

            // Click '0' window
            Mouse.Click(uIItem0Window, new Point(186, 97));

            // Type '{Back}30' in 'NumericUpDown' text box
            Keyboard.SendKeys(uINumericUpDownEdit, this.RecordedMethod1_ThemThatBai1Params.UINumericUpDownEditSendKeys, ModifierKeys.None);

            // Click 'txtDonGia' window
            Mouse.Click(uITxtDonGiaWindow, new Point(302, 99));

            // Type '3000000' in 'txtDonGia' text box
            uITxtDonGiaEdit.Text = this.RecordedMethod1_ThemThatBai1Params.UITxtDonGiaEditText;

            // Click 'txtHinhMH' window
            Mouse.Click(uITxtHinhMHWindow, new Point(392, 116));

            // Type 'png' in 'txtHinhMH' text box
            uITxtHinhMHEdit.Text = this.RecordedMethod1_ThemThatBai1Params.UITxtHinhMHEditText;

            // Click 'txtGiamGia' window
            Mouse.Click(uITxtGiamGiaWindow, new Point(255, 125));

            // Type '0' in 'txtGiamGia' text box
            uITxtGiamGiaEdit.Text = this.RecordedMethod1_ThemThatBai1Params.UITxtGiamGiaEditText;

            // Click 'txtDSHinh' window
            Mouse.Click(uITxtDSHinhWindow, new Point(313, 133));

            // Type 'png' in 'txtDSHinh' text box
            uITxtDSHinhEdit.Text = this.RecordedMethod1_ThemThatBai1Params.UITxtDSHinhEditText;

            // Click 'txtKhuyenMaiDiKem' window
            Mouse.Click(uITxtKhuyenMaiDiKemWindow, new Point(319, 125));

            // Type '0' in 'txtKhuyenMaiDiKem' text box
            uITxtKhuyenMaiDiKemEdit.Text = this.RecordedMethod1_ThemThatBai1Params.UITxtKhuyenMaiDiKemEditText;

            // Click 'txtThongTinChiTiet' window
            Mouse.Click(uITxtThongTinChiTietWindow, new Point(205, 182));

            // Click 'txtManHinh' window
            Mouse.Click(uITxtManHinhWindow, new Point(218, 79));

            // Click 'Thông tin mô tả sản phẩm' group
            Mouse.Click(uIThôngtinmôtảsảnphẩmGroup, new Point(477, 130));

            // Type 'aaaa' in 'txtManHinh' text box
            uITxtManHinhEdit.Text = this.RecordedMethod1_ThemThatBai1Params.UITxtManHinhEditText;

            // Click 'txtCameraSau' window
            Mouse.Click(uITxtCameraSauWindow, new Point(271, 87));

            // Type 'aaaa' in 'txtCameraSau' text box
            uITxtCameraSauEdit.Text = this.RecordedMethod1_ThemThatBai1Params.UITxtCameraSauEditText;

            // Click 'txtCameraSelfi' window
            Mouse.Click(uITxtCameraSelfiWindow, new Point(234, 95));

            // Type 'aaaa' in 'txtCameraSelfi' text box
            uITxtCameraSelfiEdit.Text = this.RecordedMethod1_ThemThatBai1Params.UITxtCameraSelfiEditText;

            // Click '0' window
            Mouse.Click(uIItem0Window1, new Point(218, 94));

            // Type '4' in 'NumericUpDown' text box
            Keyboard.SendKeys(uINumericUpDownEdit1, this.RecordedMethod1_ThemThatBai1Params.UINumericUpDownEditSendKeys1, ModifierKeys.None);

            // Click '0' window
            Mouse.Click(uIItem0Window2, new Point(232, 113));

            // Type '64' in 'GB' text box
            Keyboard.SendKeys(uIGBEdit, this.RecordedMethod1_ThemThatBai1Params.UIGBEditSendKeys, ModifierKeys.None);

            // Click 'txtCPU' window
            Mouse.Click(uITxtCPUWindow, new Point(246, 123));

            // Type '23' in 'txtCPU' text box
            uITxtCPUEdit.Text = this.RecordedMethod1_ThemThatBai1Params.UITxtCPUEditText;

            // Click 'txtGPU' window
            Mouse.Click(uITxtGPUWindow, new Point(232, 111));

            // Type '42' in 'txtGPU' text box
            uITxtGPUEdit.Text = this.RecordedMethod1_ThemThatBai1Params.UITxtGPUEditText;

            // Click 'txtDungLuongPin' window
            Mouse.Click(uITxtDungLuongPinWindow, new Point(219, 135));

            // Type '100' in 'txtDungLuongPin' text box
            uITxtDungLuongPinEdit.Text = this.RecordedMethod1_ThemThatBai1Params.UITxtDungLuongPinEditText;

            // Click 'txtTheSim' window
            Mouse.Click(uITxtTheSimWindow, new Point(176, 149));

            // Type '2' in 'txtTheSim' text box
            uITxtTheSimEdit.Text = this.RecordedMethod1_ThemThatBai1Params.UITxtTheSimEditText;

            // Click 'txtHeDieuHanh' window
            Mouse.Click(uITxtHeDieuHanhWindow, new Point(192, 152));

            // Type '1' in 'txtHeDieuHanh' text box
            uITxtHeDieuHanhEdit.Text = this.RecordedMethod1_ThemThatBai1Params.UITxtHeDieuHanhEditText;

            // Click 'Hoàn tất' button
            Mouse.Click(uIHoàntấtButton, new Point(1, 1));

            // Click 'Hoàn tất' button
            Mouse.Click(uIHoàntấtButton, new Point(1, 1));

            // Click 'Thêm mới' button
            Mouse.Click(uIThêmmớiButton, new Point(1, 1));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(54, 25));
        }
        
        #region Properties
        public virtual RecordedMethod1_ThemThatBai1Params RecordedMethod1_ThemThatBai1Params
        {
            get
            {
                if ((this.mRecordedMethod1_ThemThatBai1Params == null))
                {
                    this.mRecordedMethod1_ThemThatBai1Params = new RecordedMethod1_ThemThatBai1Params();
                }
                return this.mRecordedMethod1_ThemThatBai1Params;
            }
        }
        
        public UIThôngtinsảnphẩmWindow UIThôngtinsảnphẩmWindow
        {
            get
            {
                if ((this.mUIThôngtinsảnphẩmWindow == null))
                {
                    this.mUIThôngtinsảnphẩmWindow = new UIThôngtinsảnphẩmWindow();
                }
                return this.mUIThôngtinsảnphẩmWindow;
            }
        }
        
        public UIThôngtinmôtảchitiếtsWindow UIThôngtinmôtảchitiếtsWindow
        {
            get
            {
                if ((this.mUIThôngtinmôtảchitiếtsWindow == null))
                {
                    this.mUIThôngtinmôtảchitiếtsWindow = new UIThôngtinmôtảchitiếtsWindow();
                }
                return this.mUIThôngtinmôtảchitiếtsWindow;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow();
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1_ThemThatBai1Params mRecordedMethod1_ThemThatBai1Params;
        
        private UIThôngtinsảnphẩmWindow mUIThôngtinsảnphẩmWindow;
        
        private UIThôngtinmôtảchitiếtsWindow mUIThôngtinmôtảchitiếtsWindow;
        
        private UIOKWindow mUIOKWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1_ThemThatBai1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class RecordedMethod1_ThemThatBai1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'Trung Quốc' in 'txtXuatSu' text box
        /// </summary>
        public string UITxtXuatSuEditText = "Trung Quốc";
        
        /// <summary>
        /// Type '{Back}30' in 'NumericUpDown' text box
        /// </summary>
        public string UINumericUpDownEditSendKeys = "{Back}30";
        
        /// <summary>
        /// Type '3000000' in 'txtDonGia' text box
        /// </summary>
        public string UITxtDonGiaEditText = "3000000";
        
        /// <summary>
        /// Type 'png' in 'txtHinhMH' text box
        /// </summary>
        public string UITxtHinhMHEditText = "png";
        
        /// <summary>
        /// Type '0' in 'txtGiamGia' text box
        /// </summary>
        public string UITxtGiamGiaEditText = "0";
        
        /// <summary>
        /// Type 'png' in 'txtDSHinh' text box
        /// </summary>
        public string UITxtDSHinhEditText = "png";
        
        /// <summary>
        /// Type '0' in 'txtKhuyenMaiDiKem' text box
        /// </summary>
        public string UITxtKhuyenMaiDiKemEditText = "0";
        
        /// <summary>
        /// Type 'aaaa' in 'txtManHinh' text box
        /// </summary>
        public string UITxtManHinhEditText = "aaaa";
        
        /// <summary>
        /// Type 'aaaa' in 'txtCameraSau' text box
        /// </summary>
        public string UITxtCameraSauEditText = "aaaa";
        
        /// <summary>
        /// Type 'aaaa' in 'txtCameraSelfi' text box
        /// </summary>
        public string UITxtCameraSelfiEditText = "aaaa";
        
        /// <summary>
        /// Type '4' in 'NumericUpDown' text box
        /// </summary>
        public string UINumericUpDownEditSendKeys1 = "4";
        
        /// <summary>
        /// Type '64' in 'GB' text box
        /// </summary>
        public string UIGBEditSendKeys = "64";
        
        /// <summary>
        /// Type '23' in 'txtCPU' text box
        /// </summary>
        public string UITxtCPUEditText = "23";
        
        /// <summary>
        /// Type '42' in 'txtGPU' text box
        /// </summary>
        public string UITxtGPUEditText = "42";
        
        /// <summary>
        /// Type '100' in 'txtDungLuongPin' text box
        /// </summary>
        public string UITxtDungLuongPinEditText = "100";
        
        /// <summary>
        /// Type '2' in 'txtTheSim' text box
        /// </summary>
        public string UITxtTheSimEditText = "2";
        
        /// <summary>
        /// Type '1' in 'txtHeDieuHanh' text box
        /// </summary>
        public string UITxtHeDieuHanhEditText = "1";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIThôngtinsảnphẩmWindow : WinWindow
    {
        
        public UIThôngtinsảnphẩmWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Thông tin sản phẩm";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public UIThôngtinsảnphẩmGroup UIThôngtinsảnphẩmGroup
        {
            get
            {
                if ((this.mUIThôngtinsảnphẩmGroup == null))
                {
                    this.mUIThôngtinsảnphẩmGroup = new UIThôngtinsảnphẩmGroup(this);
                }
                return this.mUIThôngtinsảnphẩmGroup;
            }
        }
        
        public UITxtXuatSuWindow UITxtXuatSuWindow
        {
            get
            {
                if ((this.mUITxtXuatSuWindow == null))
                {
                    this.mUITxtXuatSuWindow = new UITxtXuatSuWindow(this);
                }
                return this.mUITxtXuatSuWindow;
            }
        }
        
        public UINumericUpDownSpinner UINumericUpDownSpinner
        {
            get
            {
                if ((this.mUINumericUpDownSpinner == null))
                {
                    this.mUINumericUpDownSpinner = new UINumericUpDownSpinner(this);
                }
                return this.mUINumericUpDownSpinner;
            }
        }
        
        public UITxtDonGiaWindow UITxtDonGiaWindow
        {
            get
            {
                if ((this.mUITxtDonGiaWindow == null))
                {
                    this.mUITxtDonGiaWindow = new UITxtDonGiaWindow(this);
                }
                return this.mUITxtDonGiaWindow;
            }
        }
        
        public UITxtHinhMHWindow UITxtHinhMHWindow
        {
            get
            {
                if ((this.mUITxtHinhMHWindow == null))
                {
                    this.mUITxtHinhMHWindow = new UITxtHinhMHWindow(this);
                }
                return this.mUITxtHinhMHWindow;
            }
        }
        
        public UITxtGiamGiaWindow UITxtGiamGiaWindow
        {
            get
            {
                if ((this.mUITxtGiamGiaWindow == null))
                {
                    this.mUITxtGiamGiaWindow = new UITxtGiamGiaWindow(this);
                }
                return this.mUITxtGiamGiaWindow;
            }
        }
        
        public UITxtDSHinhWindow UITxtDSHinhWindow
        {
            get
            {
                if ((this.mUITxtDSHinhWindow == null))
                {
                    this.mUITxtDSHinhWindow = new UITxtDSHinhWindow(this);
                }
                return this.mUITxtDSHinhWindow;
            }
        }
        
        public UITxtKhuyenMaiDiKemWindow UITxtKhuyenMaiDiKemWindow
        {
            get
            {
                if ((this.mUITxtKhuyenMaiDiKemWindow == null))
                {
                    this.mUITxtKhuyenMaiDiKemWindow = new UITxtKhuyenMaiDiKemWindow(this);
                }
                return this.mUITxtKhuyenMaiDiKemWindow;
            }
        }
        
        public DXButton UIThêmmớiButton
        {
            get
            {
                if ((this.mUIThêmmớiButton == null))
                {
                    this.mUIThêmmớiButton = new DXButton(this);
                    #region Search Criteria
                    this.mUIThêmmớiButton.SearchProperties[DXTestControl.PropertyNames.Name] = "btnThemMoi";
                    this.mUIThêmmớiButton.SearchProperties[DXTestControl.PropertyNames.ClassName] = "ButtonDesign";
                    this.mUIThêmmớiButton.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUIThêmmớiButton;
            }
        }
        #endregion
        
        #region Fields
        private UIThôngtinsảnphẩmGroup mUIThôngtinsảnphẩmGroup;
        
        private UITxtXuatSuWindow mUITxtXuatSuWindow;
        
        private UINumericUpDownSpinner mUINumericUpDownSpinner;
        
        private UITxtDonGiaWindow mUITxtDonGiaWindow;
        
        private UITxtHinhMHWindow mUITxtHinhMHWindow;
        
        private UITxtGiamGiaWindow mUITxtGiamGiaWindow;
        
        private UITxtDSHinhWindow mUITxtDSHinhWindow;
        
        private UITxtKhuyenMaiDiKemWindow mUITxtKhuyenMaiDiKemWindow;
        
        private DXButton mUIThêmmớiButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIThôngtinsảnphẩmGroup : WinGroup
    {
        
        public UIThôngtinsảnphẩmGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Thông tin sản phẩm";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinWindow UITxtXuatSuWindow
        {
            get
            {
                if ((this.mUITxtXuatSuWindow == null))
                {
                    this.mUITxtXuatSuWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtXuatSuWindow.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Xuất sứ:";
                    this.mUITxtXuatSuWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtXuatSuWindow.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtXuatSuWindow;
            }
        }
        
        public WinWindow UITxtDonGiaWindow
        {
            get
            {
                if ((this.mUITxtDonGiaWindow == null))
                {
                    this.mUITxtDonGiaWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtDonGiaWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtDonGiaWindow.SearchProperties[WinWindow.PropertyNames.Instance] = "7";
                    this.mUITxtDonGiaWindow.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtDonGiaWindow;
            }
        }
        
        public WinWindow UITxtHinhMHWindow
        {
            get
            {
                if ((this.mUITxtHinhMHWindow == null))
                {
                    this.mUITxtHinhMHWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtHinhMHWindow.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Giảm giá:";
                    this.mUITxtHinhMHWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtHinhMHWindow.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtHinhMHWindow;
            }
        }
        
        public WinWindow UITxtGiamGiaWindow
        {
            get
            {
                if ((this.mUITxtGiamGiaWindow == null))
                {
                    this.mUITxtGiamGiaWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtGiamGiaWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtGiamGiaWindow.SearchProperties[WinWindow.PropertyNames.Instance] = "3";
                    this.mUITxtGiamGiaWindow.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtGiamGiaWindow;
            }
        }
        
        public WinWindow UITxtDSHinhWindow
        {
            get
            {
                if ((this.mUITxtDSHinhWindow == null))
                {
                    this.mUITxtDSHinhWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtDSHinhWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtDSHinhWindow.SearchProperties[WinWindow.PropertyNames.Instance] = "4";
                    this.mUITxtDSHinhWindow.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtDSHinhWindow;
            }
        }
        
        public WinWindow UITxtKhuyenMaiDiKemWindow
        {
            get
            {
                if ((this.mUITxtKhuyenMaiDiKemWindow == null))
                {
                    this.mUITxtKhuyenMaiDiKemWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtKhuyenMaiDiKemWindow.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "K/Mãi đi kèm:";
                    this.mUITxtKhuyenMaiDiKemWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtKhuyenMaiDiKemWindow.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtKhuyenMaiDiKemWindow;
            }
        }
        
        public WinWindow UITxtThongTinChiTietWindow
        {
            get
            {
                if ((this.mUITxtThongTinChiTietWindow == null))
                {
                    this.mUITxtThongTinChiTietWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtThongTinChiTietWindow.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Thông tin chi tiết:";
                    this.mUITxtThongTinChiTietWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtThongTinChiTietWindow.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtThongTinChiTietWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUITxtXuatSuWindow;
        
        private WinWindow mUITxtDonGiaWindow;
        
        private WinWindow mUITxtHinhMHWindow;
        
        private WinWindow mUITxtGiamGiaWindow;
        
        private WinWindow mUITxtDSHinhWindow;
        
        private WinWindow mUITxtKhuyenMaiDiKemWindow;
        
        private WinWindow mUITxtThongTinChiTietWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtXuatSuWindow : WinWindow
    {
        
        public UITxtXuatSuWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtXuatSu";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtXuatSuEdit
        {
            get
            {
                if ((this.mUITxtXuatSuEdit == null))
                {
                    this.mUITxtXuatSuEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtXuatSuEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Xuất sứ:";
                    this.mUITxtXuatSuEdit.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtXuatSuEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtXuatSuEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UINumericUpDownSpinner : WinSpinner
    {
        
        public UINumericUpDownSpinner(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinSpinner.PropertyNames.Name] = "NumericUpDown";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinWindow UIItem0Window
        {
            get
            {
                if ((this.mUIItem0Window == null))
                {
                    this.mUIItem0Window = new WinWindow(this);
                    #region Search Criteria
                    this.mUIItem0Window.SearchProperties[WinWindow.PropertyNames.Name] = "0";
                    this.mUIItem0Window.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUIItem0Window.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUIItem0Window;
            }
        }
        
        public WinEdit UINumericUpDownEdit
        {
            get
            {
                if ((this.mUINumericUpDownEdit == null))
                {
                    this.mUINumericUpDownEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUINumericUpDownEdit.SearchProperties[WinEdit.PropertyNames.Name] = "NumericUpDown";
                    this.mUINumericUpDownEdit.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUINumericUpDownEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIItem0Window;
        
        private WinEdit mUINumericUpDownEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtDonGiaWindow : WinWindow
    {
        
        public UITxtDonGiaWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtDonGia";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtDonGiaEdit
        {
            get
            {
                if ((this.mUITxtDonGiaEdit == null))
                {
                    this.mUITxtDonGiaEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtDonGiaEdit.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtDonGiaEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtDonGiaEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtHinhMHWindow : WinWindow
    {
        
        public UITxtHinhMHWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtHinhMH";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtHinhMHEdit
        {
            get
            {
                if ((this.mUITxtHinhMHEdit == null))
                {
                    this.mUITxtHinhMHEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtHinhMHEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Giảm giá:";
                    this.mUITxtHinhMHEdit.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtHinhMHEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtHinhMHEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtGiamGiaWindow : WinWindow
    {
        
        public UITxtGiamGiaWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtGiamGia";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtGiamGiaEdit
        {
            get
            {
                if ((this.mUITxtGiamGiaEdit == null))
                {
                    this.mUITxtGiamGiaEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtGiamGiaEdit.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtGiamGiaEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtGiamGiaEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtDSHinhWindow : WinWindow
    {
        
        public UITxtDSHinhWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtDSHinh";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtDSHinhEdit
        {
            get
            {
                if ((this.mUITxtDSHinhEdit == null))
                {
                    this.mUITxtDSHinhEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtDSHinhEdit.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtDSHinhEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtDSHinhEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtKhuyenMaiDiKemWindow : WinWindow
    {
        
        public UITxtKhuyenMaiDiKemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtKhuyenMaiDiKem";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtKhuyenMaiDiKemEdit
        {
            get
            {
                if ((this.mUITxtKhuyenMaiDiKemEdit == null))
                {
                    this.mUITxtKhuyenMaiDiKemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtKhuyenMaiDiKemEdit.SearchProperties[WinEdit.PropertyNames.Name] = "K/Mãi đi kèm:";
                    this.mUITxtKhuyenMaiDiKemEdit.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtKhuyenMaiDiKemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtKhuyenMaiDiKemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIThôngtinmôtảchitiếtsWindow : WinWindow
    {
        
        public UIThôngtinmôtảchitiếtsWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Thông tin mô tả chi tiết sản phẩm";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public UIThôngtinmôtảsảnphẩmGroup UIThôngtinmôtảsảnphẩmGroup
        {
            get
            {
                if ((this.mUIThôngtinmôtảsảnphẩmGroup == null))
                {
                    this.mUIThôngtinmôtảsảnphẩmGroup = new UIThôngtinmôtảsảnphẩmGroup(this);
                }
                return this.mUIThôngtinmôtảsảnphẩmGroup;
            }
        }
        
        public UIThôngtinmôtảsảnphẩmWindow UIThôngtinmôtảsảnphẩmWindow
        {
            get
            {
                if ((this.mUIThôngtinmôtảsảnphẩmWindow == null))
                {
                    this.mUIThôngtinmôtảsảnphẩmWindow = new UIThôngtinmôtảsảnphẩmWindow(this);
                }
                return this.mUIThôngtinmôtảsảnphẩmWindow;
            }
        }
        
        public UITxtManHinhWindow UITxtManHinhWindow
        {
            get
            {
                if ((this.mUITxtManHinhWindow == null))
                {
                    this.mUITxtManHinhWindow = new UITxtManHinhWindow(this);
                }
                return this.mUITxtManHinhWindow;
            }
        }
        
        public UITxtCameraSauWindow UITxtCameraSauWindow
        {
            get
            {
                if ((this.mUITxtCameraSauWindow == null))
                {
                    this.mUITxtCameraSauWindow = new UITxtCameraSauWindow(this);
                }
                return this.mUITxtCameraSauWindow;
            }
        }
        
        public UITxtCameraSelfiWindow UITxtCameraSelfiWindow
        {
            get
            {
                if ((this.mUITxtCameraSelfiWindow == null))
                {
                    this.mUITxtCameraSelfiWindow = new UITxtCameraSelfiWindow(this);
                }
                return this.mUITxtCameraSelfiWindow;
            }
        }
        
        public UINumericUpDownSpinner1 UINumericUpDownSpinner
        {
            get
            {
                if ((this.mUINumericUpDownSpinner == null))
                {
                    this.mUINumericUpDownSpinner = new UINumericUpDownSpinner1(this);
                }
                return this.mUINumericUpDownSpinner;
            }
        }
        
        public UIGBSpinner UIGBSpinner
        {
            get
            {
                if ((this.mUIGBSpinner == null))
                {
                    this.mUIGBSpinner = new UIGBSpinner(this);
                }
                return this.mUIGBSpinner;
            }
        }
        
        public UITxtCPUWindow UITxtCPUWindow
        {
            get
            {
                if ((this.mUITxtCPUWindow == null))
                {
                    this.mUITxtCPUWindow = new UITxtCPUWindow(this);
                }
                return this.mUITxtCPUWindow;
            }
        }
        
        public UITxtGPUWindow UITxtGPUWindow
        {
            get
            {
                if ((this.mUITxtGPUWindow == null))
                {
                    this.mUITxtGPUWindow = new UITxtGPUWindow(this);
                }
                return this.mUITxtGPUWindow;
            }
        }
        
        public UITxtDungLuongPinWindow UITxtDungLuongPinWindow
        {
            get
            {
                if ((this.mUITxtDungLuongPinWindow == null))
                {
                    this.mUITxtDungLuongPinWindow = new UITxtDungLuongPinWindow(this);
                }
                return this.mUITxtDungLuongPinWindow;
            }
        }
        
        public UITxtTheSimWindow UITxtTheSimWindow
        {
            get
            {
                if ((this.mUITxtTheSimWindow == null))
                {
                    this.mUITxtTheSimWindow = new UITxtTheSimWindow(this);
                }
                return this.mUITxtTheSimWindow;
            }
        }
        
        public UITxtHeDieuHanhWindow UITxtHeDieuHanhWindow
        {
            get
            {
                if ((this.mUITxtHeDieuHanhWindow == null))
                {
                    this.mUITxtHeDieuHanhWindow = new UITxtHeDieuHanhWindow(this);
                }
                return this.mUITxtHeDieuHanhWindow;
            }
        }
        
        public DXButton UIHoàntấtButton
        {
            get
            {
                if ((this.mUIHoàntấtButton == null))
                {
                    this.mUIHoàntấtButton = new DXButton(this);
                    #region Search Criteria
                    this.mUIHoàntấtButton.SearchProperties[DXTestControl.PropertyNames.Name] = "btnHoatTat";
                    this.mUIHoàntấtButton.SearchProperties[DXTestControl.PropertyNames.ClassName] = "ButtonDesign";
                    this.mUIHoàntấtButton.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUIHoàntấtButton;
            }
        }
        #endregion
        
        #region Fields
        private UIThôngtinmôtảsảnphẩmGroup mUIThôngtinmôtảsảnphẩmGroup;
        
        private UIThôngtinmôtảsảnphẩmWindow mUIThôngtinmôtảsảnphẩmWindow;
        
        private UITxtManHinhWindow mUITxtManHinhWindow;
        
        private UITxtCameraSauWindow mUITxtCameraSauWindow;
        
        private UITxtCameraSelfiWindow mUITxtCameraSelfiWindow;
        
        private UINumericUpDownSpinner1 mUINumericUpDownSpinner;
        
        private UIGBSpinner mUIGBSpinner;
        
        private UITxtCPUWindow mUITxtCPUWindow;
        
        private UITxtGPUWindow mUITxtGPUWindow;
        
        private UITxtDungLuongPinWindow mUITxtDungLuongPinWindow;
        
        private UITxtTheSimWindow mUITxtTheSimWindow;
        
        private UITxtHeDieuHanhWindow mUITxtHeDieuHanhWindow;
        
        private DXButton mUIHoàntấtButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIThôngtinmôtảsảnphẩmGroup : WinGroup
    {
        
        public UIThôngtinmôtảsảnphẩmGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Thông tin mô tả sản phẩm";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinWindow UITxtManHinhWindow
        {
            get
            {
                if ((this.mUITxtManHinhWindow == null))
                {
                    this.mUITxtManHinhWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtManHinhWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtManHinhWindow.SearchProperties[WinWindow.PropertyNames.Instance] = "10";
                    this.mUITxtManHinhWindow.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtManHinhWindow;
            }
        }
        
        public WinWindow UITxtCameraSauWindow
        {
            get
            {
                if ((this.mUITxtCameraSauWindow == null))
                {
                    this.mUITxtCameraSauWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtCameraSauWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtCameraSauWindow.SearchProperties[WinWindow.PropertyNames.Instance] = "9";
                    this.mUITxtCameraSauWindow.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtCameraSauWindow;
            }
        }
        
        public WinWindow UITxtCameraSelfiWindow
        {
            get
            {
                if ((this.mUITxtCameraSelfiWindow == null))
                {
                    this.mUITxtCameraSelfiWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtCameraSelfiWindow.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Màn hình:";
                    this.mUITxtCameraSelfiWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtCameraSelfiWindow.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtCameraSelfiWindow;
            }
        }
        
        public WinWindow UITxtCPUWindow
        {
            get
            {
                if ((this.mUITxtCPUWindow == null))
                {
                    this.mUITxtCPUWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtCPUWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtCPUWindow.SearchProperties[WinWindow.PropertyNames.Instance] = "5";
                    this.mUITxtCPUWindow.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtCPUWindow;
            }
        }
        
        public WinWindow UITxtGPUWindow
        {
            get
            {
                if ((this.mUITxtGPUWindow == null))
                {
                    this.mUITxtGPUWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtGPUWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtGPUWindow.SearchProperties[WinWindow.PropertyNames.Instance] = "4";
                    this.mUITxtGPUWindow.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtGPUWindow;
            }
        }
        
        public WinWindow UITxtDungLuongPinWindow
        {
            get
            {
                if ((this.mUITxtDungLuongPinWindow == null))
                {
                    this.mUITxtDungLuongPinWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtDungLuongPinWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtDungLuongPinWindow.SearchProperties[WinWindow.PropertyNames.Instance] = "3";
                    this.mUITxtDungLuongPinWindow.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtDungLuongPinWindow;
            }
        }
        
        public WinWindow UITxtTheSimWindow
        {
            get
            {
                if ((this.mUITxtTheSimWindow == null))
                {
                    this.mUITxtTheSimWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtTheSimWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtTheSimWindow.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
                    this.mUITxtTheSimWindow.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtTheSimWindow;
            }
        }
        
        public WinWindow UITxtHeDieuHanhWindow
        {
            get
            {
                if ((this.mUITxtHeDieuHanhWindow == null))
                {
                    this.mUITxtHeDieuHanhWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtHeDieuHanhWindow.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "CPU:";
                    this.mUITxtHeDieuHanhWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtHeDieuHanhWindow.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtHeDieuHanhWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUITxtManHinhWindow;
        
        private WinWindow mUITxtCameraSauWindow;
        
        private WinWindow mUITxtCameraSelfiWindow;
        
        private WinWindow mUITxtCPUWindow;
        
        private WinWindow mUITxtGPUWindow;
        
        private WinWindow mUITxtDungLuongPinWindow;
        
        private WinWindow mUITxtTheSimWindow;
        
        private WinWindow mUITxtHeDieuHanhWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIThôngtinmôtảsảnphẩmWindow : WinWindow
    {
        
        public UIThôngtinmôtảsảnphẩmWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "groupBox1";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinGroup UIThôngtinmôtảsảnphẩmGroup
        {
            get
            {
                if ((this.mUIThôngtinmôtảsảnphẩmGroup == null))
                {
                    this.mUIThôngtinmôtảsảnphẩmGroup = new WinGroup(this);
                    #region Search Criteria
                    this.mUIThôngtinmôtảsảnphẩmGroup.SearchProperties[WinControl.PropertyNames.Name] = "Thông tin mô tả sản phẩm";
                    this.mUIThôngtinmôtảsảnphẩmGroup.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUIThôngtinmôtảsảnphẩmGroup;
            }
        }
        #endregion
        
        #region Fields
        private WinGroup mUIThôngtinmôtảsảnphẩmGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtManHinhWindow : WinWindow
    {
        
        public UITxtManHinhWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtManHinh";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtManHinhEdit
        {
            get
            {
                if ((this.mUITxtManHinhEdit == null))
                {
                    this.mUITxtManHinhEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtManHinhEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtManHinhEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtManHinhEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtCameraSauWindow : WinWindow
    {
        
        public UITxtCameraSauWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtCameraSau";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtCameraSauEdit
        {
            get
            {
                if ((this.mUITxtCameraSauEdit == null))
                {
                    this.mUITxtCameraSauEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtCameraSauEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtCameraSauEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtCameraSauEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtCameraSelfiWindow : WinWindow
    {
        
        public UITxtCameraSelfiWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtCameraSelfi";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtCameraSelfiEdit
        {
            get
            {
                if ((this.mUITxtCameraSelfiEdit == null))
                {
                    this.mUITxtCameraSelfiEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtCameraSelfiEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Màn hình:";
                    this.mUITxtCameraSelfiEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtCameraSelfiEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtCameraSelfiEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UINumericUpDownSpinner1 : WinSpinner
    {
        
        public UINumericUpDownSpinner1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinSpinner.PropertyNames.Name] = "NumericUpDown";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinWindow UIItem0Window
        {
            get
            {
                if ((this.mUIItem0Window == null))
                {
                    this.mUIItem0Window = new WinWindow(this);
                    #region Search Criteria
                    this.mUIItem0Window.SearchProperties[WinWindow.PropertyNames.Name] = "0";
                    this.mUIItem0Window.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUIItem0Window.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUIItem0Window;
            }
        }
        
        public WinEdit UINumericUpDownEdit
        {
            get
            {
                if ((this.mUINumericUpDownEdit == null))
                {
                    this.mUINumericUpDownEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUINumericUpDownEdit.SearchProperties[WinEdit.PropertyNames.Name] = "NumericUpDown";
                    this.mUINumericUpDownEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUINumericUpDownEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIItem0Window;
        
        private WinEdit mUINumericUpDownEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIGBSpinner : WinSpinner
    {
        
        public UIGBSpinner(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinSpinner.PropertyNames.Name] = "GB";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinWindow UIItem0Window
        {
            get
            {
                if ((this.mUIItem0Window == null))
                {
                    this.mUIItem0Window = new WinWindow(this);
                    #region Search Criteria
                    this.mUIItem0Window.SearchProperties[WinWindow.PropertyNames.Name] = "0";
                    this.mUIItem0Window.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUIItem0Window.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUIItem0Window;
            }
        }
        
        public WinEdit UIGBEdit
        {
            get
            {
                if ((this.mUIGBEdit == null))
                {
                    this.mUIGBEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIGBEdit.SearchProperties[WinEdit.PropertyNames.Name] = "GB";
                    this.mUIGBEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUIGBEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIItem0Window;
        
        private WinEdit mUIGBEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtCPUWindow : WinWindow
    {
        
        public UITxtCPUWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtCPU";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtCPUEdit
        {
            get
            {
                if ((this.mUITxtCPUEdit == null))
                {
                    this.mUITxtCPUEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtCPUEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtCPUEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtCPUEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtGPUWindow : WinWindow
    {
        
        public UITxtGPUWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtGPU";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtGPUEdit
        {
            get
            {
                if ((this.mUITxtGPUEdit == null))
                {
                    this.mUITxtGPUEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtGPUEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtGPUEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtGPUEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtDungLuongPinWindow : WinWindow
    {
        
        public UITxtDungLuongPinWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtDungLuongPin";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtDungLuongPinEdit
        {
            get
            {
                if ((this.mUITxtDungLuongPinEdit == null))
                {
                    this.mUITxtDungLuongPinEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtDungLuongPinEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtDungLuongPinEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtDungLuongPinEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtTheSimWindow : WinWindow
    {
        
        public UITxtTheSimWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtTheSim";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtTheSimEdit
        {
            get
            {
                if ((this.mUITxtTheSimEdit == null))
                {
                    this.mUITxtTheSimEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtTheSimEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtTheSimEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtTheSimEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtHeDieuHanhWindow : WinWindow
    {
        
        public UITxtHeDieuHanhWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtHeDieuHanh";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtHeDieuHanhEdit
        {
            get
            {
                if ((this.mUITxtHeDieuHanhEdit == null))
                {
                    this.mUITxtHeDieuHanhEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtHeDieuHanhEdit.SearchProperties[WinEdit.PropertyNames.Name] = "CPU:";
                    this.mUITxtHeDieuHanhEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtHeDieuHanhEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtHeDieuHanhEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "OK";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("OK");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("OK");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
}
