// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 16.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUI_QLSanPhamDienTu
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using DevExpress.CodedUIExtension.DXTestControls.v19_2;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Khong them day du thong tin
        /// </summary>
        public void RecordedMethod1_ThemThatBai()
        {
            #region Variable Declarations
            DXButton uIThêmsảnphẩmButton = this.UISảnphẩmWindow.UIPanelControl1Client.UIThêmsảnphẩmButton;
            WinEdit uITxtTenSPEdit = this.UIThôngtinsảnphẩmWindow.UITxtTenSPWindow.UITxtTenSPEdit;
            WinEdit uITxtXuatSuEdit = this.UIThôngtinsảnphẩmWindow.UITxtXuatSuWindow.UITxtXuatSuEdit;
            WinEdit uITxtDonGiaEdit = this.UIThôngtinsảnphẩmWindow.UITxtDonGiaWindow.UITxtDonGiaEdit;
            WinEdit uITextEditorEdit = this.UITesttxtNotepadWindow.UIItemWindow.UITextEditorEdit;
            WinEdit uINumericUpDownEdit = this.UIThôngtinsảnphẩmWindow.UINumericUpDownSpinner.UINumericUpDownEdit;
            WinEdit uITxtHinhMHEdit = this.UIThôngtinsảnphẩmWindow.UITxtHinhMHWindow.UITxtHinhMHEdit;
            WinEdit uITxtGiamGiaEdit = this.UIThôngtinsảnphẩmWindow.UITxtGiamGiaWindow.UITxtGiamGiaEdit;
            WinEdit uITxtDSHinhEdit = this.UIThôngtinsảnphẩmWindow.UITxtDSHinhWindow.UITxtDSHinhEdit;
            WinEdit uITxtKhuyenMaiDiKemEdit = this.UIThôngtinsảnphẩmWindow.UITxtKhuyenMaiDiKemWindow.UITxtKhuyenMaiDiKemEdit;
            WinEdit uITxtThongTinChiTietEdit = this.UIThôngtinsảnphẩmWindow.UITxtThongTinChiTietWindow.UITxtThongTinChiTietEdit;
            WinGroup uIThôngtinmôtảsảnphẩmGroup = this.UIThôngtinmôtảchitiếtsWindow.UIThôngtinmôtảsảnphẩmWindow.UIThôngtinmôtảsảnphẩmGroup;
            WinEdit uITxtManHinhEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtManHinhWindow.UITxtManHinhEdit;
            WinEdit uITxtCameraSauEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtCameraSauWindow.UITxtCameraSauEdit;
            WinEdit uIGBEdit = this.UIThôngtinmôtảchitiếtsWindow.UIGBSpinner.UIGBEdit;
            WinSpinner uINumericUpDownSpinner = this.UIThôngtinmôtảchitiếtsWindow.UINumRAMWindow.UINumericUpDownSpinner;
            WinEdit uINumericUpDownEdit1 = this.UIThôngtinmôtảchitiếtsWindow.UINumericUpDownSpinner.UINumericUpDownEdit;
            WinEdit uITxtCameraSelfiEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtCameraSelfiWindow.UITxtCameraSelfiEdit;
            WinEdit uITxtCPUEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtCPUWindow.UITxtCPUEdit;
            WinEdit uITxtGPUEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtGPUWindow.UITxtGPUEdit;
            WinEdit uITxtDungLuongPinEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtDungLuongPinWindow.UITxtDungLuongPinEdit;
            WinEdit uITxtTheSimEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtTheSimWindow.UITxtTheSimEdit;
            WinEdit uITxtHeDieuHanhEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtHeDieuHanhWindow.UITxtHeDieuHanhEdit;
            DXButton uIHoàntấtButton = this.UIThôngtinmôtảchitiếtsWindow.UIHoàntấtButton;
            WinCheckBox uITìnhtrạngCònhàngCheckBox = this.UIThôngtinsảnphẩmWindow.UITìnhtrạngCònhàngWindow.UITìnhtrạngCònhàngCheckBox;
            DXButton uIThêmmớiButton = this.UIThôngtinsảnphẩmWindow.UIThêmmớiButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            #endregion

            // Click 'Thêm sản phẩm' button
            Mouse.Click(uIThêmsảnphẩmButton, new Point(1, 1));

            // Click 'txtTenSP' text box
            Mouse.Click(uITxtTenSPEdit, new Point(200, 5));

            // Type 'Trung Quốc' in 'txtXuatSu' text box
            uITxtXuatSuEdit.Text = this.RecordedMethod1_ThemThatBaiParams.UITxtXuatSuEditText;

            // Click 'txtDonGia' text box
            Mouse.Click(uITxtDonGiaEdit, new Point(53, 14));

            // Move 'Text Editor' text box
            Mouse.StartDragging(uITextEditorEdit, new Point(196, 65));
            Mouse.StopDragging(uITextEditorEdit, -99, -12);

            // Type 'Control + c' in 'Text Editor' text box
            Keyboard.SendKeys(uITextEditorEdit, this.RecordedMethod1_ThemThatBaiParams.UITextEditorEditSendKeys, ModifierKeys.Control);

            // Type '29990000' in 'txtDonGia' text box
            uITxtDonGiaEdit.Text = this.RecordedMethod1_ThemThatBaiParams.UITxtDonGiaEditText;

            // Click 'NumericUpDown' text box
            Mouse.Click(uINumericUpDownEdit, new Point(89, 18));

            // Type '120' in 'NumericUpDown' text box
            Keyboard.SendKeys(uINumericUpDownEdit, this.RecordedMethod1_ThemThatBaiParams.UINumericUpDownEditSendKeys, ModifierKeys.None);

            // Type 'png' in 'txtHinhMH' text box
            uITxtHinhMHEdit.Text = this.RecordedMethod1_ThemThatBaiParams.UITxtHinhMHEditText;

            // Type '0' in 'txtGiamGia' text box
            uITxtGiamGiaEdit.Text = this.RecordedMethod1_ThemThatBaiParams.UITxtGiamGiaEditText;

            // Type 'png' in 'txtDSHinh' text box
            uITxtDSHinhEdit.Text = this.RecordedMethod1_ThemThatBaiParams.UITxtDSHinhEditText;

            // Type '0' in 'txtKhuyenMaiDiKem' text box
            uITxtKhuyenMaiDiKemEdit.Text = this.RecordedMethod1_ThemThatBaiParams.UITxtKhuyenMaiDiKemEditText;

            // Click 'txtThongTinChiTiet' text box
            Mouse.Click(uITxtThongTinChiTietEdit, new Point(190, 34));

            // Move 'Text Editor' text box
            Mouse.StartDragging(uITextEditorEdit, new Point(624, 73));
            Mouse.StopDragging(uITextEditorEdit, -521, 13);

            // Type 'Control + c' in 'Text Editor' text box
            Keyboard.SendKeys(uITextEditorEdit, this.RecordedMethod1_ThemThatBaiParams.UITextEditorEditSendKeys1, ModifierKeys.Control);

            // Click 'Thông tin mô tả sản phẩm' group
            Mouse.Click(uIThôngtinmôtảsảnphẩmGroup, new Point(472, 171));

            // Type '6.7", Super Retina XDR, AMOLED, 2778 x 1284 Pixel' in 'txtManHinh' text box
            uITxtManHinhEdit.Text = this.RecordedMethod1_ThemThatBaiParams.UITxtManHinhEditText;

            // Move 'Text Editor' text box
            Mouse.StartDragging(uITextEditorEdit, new Point(284, 93));
            Mouse.StopDragging(uITextEditorEdit, -143, 1);

            // Click 'Text Editor' text box
            Mouse.Click(uITextEditorEdit, new Point(261, 93));

            // Move 'Text Editor' text box
            Mouse.StartDragging(uITextEditorEdit, new Point(298, 103));
            Mouse.StopDragging(uITextEditorEdit, -172, -3);

            // Type 'Control + c' in 'Text Editor' text box
            Keyboard.SendKeys(uITextEditorEdit, this.RecordedMethod1_ThemThatBaiParams.UITextEditorEditSendKeys2, ModifierKeys.Control);

            // Type '12.0 MP + 12.0' in 'txtCameraSau' text box
            uITxtCameraSauEdit.Text = this.RecordedMethod1_ThemThatBaiParams.UITxtCameraSauEditText;

            // Move 'Text Editor' text box
            Mouse.StartDragging(uITextEditorEdit, new Point(356, 142));
            Mouse.StopDragging(uITextEditorEdit, -212, 2);

            // Type 'Control + c' in 'Text Editor' text box
            Keyboard.SendKeys(uITextEditorEdit, this.RecordedMethod1_ThemThatBaiParams.UITextEditorEditSendKeys3, ModifierKeys.Control);

            // Type '{LMenu}' in 'Text Editor' text box
            Keyboard.SendKeys(uITextEditorEdit, this.RecordedMethod1_ThemThatBaiParams.UITextEditorEditSendKeys4, ModifierKeys.None);

            // Click 'GB' text box
            Mouse.Click(uIGBEdit, new Point(69, 8));

            // Type 'Control + v' in 'GB' text box
            Keyboard.SendKeys(uIGBEdit, this.RecordedMethod1_ThemThatBaiParams.UIGBEditSendKeys, ModifierKeys.Control);

            // Click 'GB' text box
            Mouse.Click(uIGBEdit, new Point(23, 3));

            // Type '128' in 'GB' text box
            Keyboard.SendKeys(uIGBEdit, this.RecordedMethod1_ThemThatBaiParams.UIGBEditSendKeys1, ModifierKeys.None);

            // Click 'NumericUpDown' spinner
            Mouse.Click(uINumericUpDownSpinner, new Point(29, 23));

            // Click 'NumericUpDown' text box
            Mouse.Click(uINumericUpDownEdit1, new Point(31, 12));

            // Type '6' in 'NumericUpDown' text box
            Keyboard.SendKeys(uINumericUpDownEdit1, this.RecordedMethod1_ThemThatBaiParams.UINumericUpDownEditSendKeys1, ModifierKeys.None);

            // Move 'Text Editor' text box
            Mouse.StartDragging(uITextEditorEdit, new Point(225, 167));
            Mouse.StopDragging(uITextEditorEdit, -81, -6);

            // Type 'Control + c' in 'Text Editor' text box
            Keyboard.SendKeys(uITextEditorEdit, this.RecordedMethod1_ThemThatBaiParams.UITextEditorEditSendKeys5, ModifierKeys.Control);

            // Type '12.0 MP' in 'txtCameraSelfi' text box
            uITxtCameraSelfiEdit.Text = this.RecordedMethod1_ThemThatBaiParams.UITxtCameraSelfiEditText;

            // Click 'txtCPU' text box
            Mouse.Click(uITxtCPUEdit, new Point(90, 4));

            // Move 'Text Editor' text box
            Mouse.StartDragging(uITextEditorEdit, new Point(192, 200));
            Mouse.StopDragging(uITextEditorEdit, -105, -14);

            // Click 'Text Editor' text box
            Mouse.Click(uITextEditorEdit, new Point(145, 194));

            // Move 'Text Editor' text box
            Mouse.StartDragging(uITextEditorEdit, new Point(173, 192));
            Mouse.StopDragging(uITextEditorEdit, -117, 0);

            // Type 'Control + c' in 'Text Editor' text box
            Keyboard.SendKeys(uITextEditorEdit, this.RecordedMethod1_ThemThatBaiParams.UITextEditorEditSendKeys6, ModifierKeys.Control);

            // Type 'A14 Bionic' in 'txtCPU' text box
            uITxtCPUEdit.Text = this.RecordedMethod1_ThemThatBaiParams.UITxtCPUEditText;

            // Move 'Text Editor' text box
            Mouse.StartDragging(uITextEditorEdit, new Point(226, 212));
            Mouse.StopDragging(uITextEditorEdit, -176, -1);

            // Type 'Control + c' in 'Text Editor' text box
            Keyboard.SendKeys(uITextEditorEdit, this.RecordedMethod1_ThemThatBaiParams.UITextEditorEditSendKeys7, ModifierKeys.Control);

            // Type 'Apple GPU 4 nhân' in 'txtGPU' text box
            uITxtGPUEdit.Text = this.RecordedMethod1_ThemThatBaiParams.UITxtGPUEditText;

            // Click 'txtDungLuongPin' text box
            Mouse.Click(uITxtDungLuongPinEdit, new Point(62, 7));

            // Move 'Text Editor' text box
            Mouse.StartDragging(uITextEditorEdit, new Point(248, 227));
            Mouse.StopDragging(uITextEditorEdit, -81, -3);

            // Type 'Control + c' in 'Text Editor' text box
            Keyboard.SendKeys(uITextEditorEdit, this.RecordedMethod1_ThemThatBaiParams.UITextEditorEditSendKeys8, ModifierKeys.Control);

            // Type '3687 mAh' in 'txtDungLuongPin' text box
            uITxtDungLuongPinEdit.Text = this.RecordedMethod1_ThemThatBaiParams.UITxtDungLuongPinEditText;

            // Move 'Text Editor' text box
            Mouse.StartDragging(uITextEditorEdit, new Point(324, 253));
            Mouse.StopDragging(uITextEditorEdit, -226, 5);

            // Type 'Control + c' in 'Text Editor' text box
            Keyboard.SendKeys(uITextEditorEdit, this.RecordedMethod1_ThemThatBaiParams.UITextEditorEditSendKeys9, ModifierKeys.Control);

            // Type '1 eSIM, 1 Nano SIM' in 'txtTheSim' text box
            uITxtTheSimEdit.Text = this.RecordedMethod1_ThemThatBaiParams.UITxtTheSimEditText;

            // Move 'Text Editor' text box
            Mouse.StartDragging(uITextEditorEdit, new Point(220, 275));
            Mouse.StopDragging(uITextEditorEdit, -76, 6);

            // Type 'Control + c' in 'Text Editor' text box
            Keyboard.SendKeys(uITextEditorEdit, this.RecordedMethod1_ThemThatBaiParams.UITextEditorEditSendKeys10, ModifierKeys.Control);

            // Type 'iOS 14' in 'txtHeDieuHanh' text box
            uITxtHeDieuHanhEdit.Text = this.RecordedMethod1_ThemThatBaiParams.UITxtHeDieuHanhEditText;

            // Click 'Hoàn tất' button
            Mouse.Click(uIHoàntấtButton, new Point(1, 1));

            // Select 'Tình trạng (Còn hàng)' check box
            uITìnhtrạngCònhàngCheckBox.Checked = this.RecordedMethod1_ThemThatBaiParams.UITìnhtrạngCònhàngCheckBoxChecked;

            // Click 'Thêm mới' button
            Mouse.Click(uIThêmmớiButton, new Point(1, 1));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(64, 22));
        }
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            DXButton uIThêmsảnphẩmButton = this.UISảnphẩmWindow.UIPanelControl1Client.UIThêmsảnphẩmButton;
            WinEdit uITxtTenSPEdit = this.UIThôngtinsảnphẩmWindow.UITxtTenSPWindow.UITxtTenSPEdit;
            WinDateTimePicker uIPickerNgayCNDateTimePicker = this.UIThôngtinsảnphẩmWindow.UIPickerNgayCNWindow.UIPickerNgayCNDateTimePicker;
            WinEdit uITxtXuatSuEdit = this.UIThôngtinsảnphẩmWindow.UITxtXuatSuWindow.UITxtXuatSuEdit;
            WinEdit uINumericUpDownEdit = this.UIThôngtinsảnphẩmWindow.UINumericUpDownSpinner.UINumericUpDownEdit;
            WinEdit uITxtDonGiaEdit = this.UIThôngtinsảnphẩmWindow.UITxtDonGiaWindow.UITxtDonGiaEdit;
            WinEdit uITxtHinhMHEdit = this.UIThôngtinsảnphẩmWindow.UITxtHinhMHWindow.UITxtHinhMHEdit;
            WinEdit uITxtGiamGiaEdit = this.UIThôngtinsảnphẩmWindow.UITxtGiamGiaWindow.UITxtGiamGiaEdit;
            WinEdit uITxtDSHinhEdit = this.UIThôngtinsảnphẩmWindow.UITxtDSHinhWindow.UITxtDSHinhEdit;
            WinEdit uITxtKhuyenMaiDiKemEdit = this.UIThôngtinsảnphẩmWindow.UITxtKhuyenMaiDiKemWindow.UITxtKhuyenMaiDiKemEdit;
            WinEdit uITxtThongTinChiTietEdit = this.UIThôngtinsảnphẩmWindow.UITxtThongTinChiTietWindow.UITxtThongTinChiTietEdit;
            WinEdit uITxtManHinhEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtManHinhWindow.UITxtManHinhEdit;
            WinEdit uITxtCameraSauEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtCameraSauWindow.UITxtCameraSauEdit;
            WinEdit uITxtCameraSelfiEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtCameraSelfiWindow.UITxtCameraSelfiEdit;
            WinEdit uINumericUpDownEdit1 = this.UIThôngtinmôtảchitiếtsWindow.UINumericUpDownSpinner.UINumericUpDownEdit;
            WinEdit uIGBEdit = this.UIThôngtinmôtảchitiếtsWindow.UIGBSpinner.UIGBEdit;
            WinEdit uITxtCPUEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtCPUWindow.UITxtCPUEdit;
            WinEdit uITxtGPUEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtGPUWindow.UITxtGPUEdit;
            WinEdit uITxtDungLuongPinEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtDungLuongPinWindow.UITxtDungLuongPinEdit;
            WinEdit uITxtTheSimEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtTheSimWindow.UITxtTheSimEdit;
            WinEdit uITxtHeDieuHanhEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtHeDieuHanhWindow.UITxtHeDieuHanhEdit;
            DXButton uIHoàntấtButton = this.UIThôngtinmôtảchitiếtsWindow.UIHoàntấtButton;
            WinCheckBox uITìnhtrạngCònhàngCheckBox = this.UIThôngtinsảnphẩmWindow.UITìnhtrạngCònhàngWindow.UITìnhtrạngCònhàngCheckBox;
            DXButton uIThêmmớiButton = this.UIThôngtinsảnphẩmWindow.UIThêmmớiButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            #endregion

            // Click 'Thêm sản phẩm' button
            Mouse.Click(uIThêmsảnphẩmButton, new Point(1, 1));

            // Click 'txtTenSP' text box
            Mouse.Click(uITxtTenSPEdit, new Point(77, 4));

            // Click 'pickerNgayCN' date time picker
            Mouse.Click(uIPickerNgayCNDateTimePicker, new Point(159, 2));

            // Click 'pickerNgayCN' date time picker
            Mouse.Click(uIPickerNgayCNDateTimePicker, new Point(117, 18));

            // Click 'txtXuatSu' text box
            Mouse.Click(uITxtXuatSuEdit, new Point(79, 17));

            // Click 'NumericUpDown' text box
            Mouse.Click(uINumericUpDownEdit, new Point(56, 17));

            // Click 'txtDonGia' text box
            Mouse.Click(uITxtDonGiaEdit, new Point(36, 14));

            // Click 'txtHinhMH' text box
            Mouse.Click(uITxtHinhMHEdit, new Point(250, 5));

            // Click 'txtGiamGia' text box
            Mouse.Click(uITxtGiamGiaEdit, new Point(109, 14));

            // Click 'txtDSHinh' text box
            Mouse.Click(uITxtDSHinhEdit, new Point(47, 5));

            // Click 'txtKhuyenMaiDiKem' text box
            Mouse.Click(uITxtKhuyenMaiDiKemEdit, new Point(242, 14));

            // Click 'txtThongTinChiTiet' text box
            Mouse.Click(uITxtThongTinChiTietEdit, new Point(194, 32));

            // Click 'txtManHinh' text box
            Mouse.Click(uITxtManHinhEdit, new Point(39, 10));

            // Click 'txtCameraSau' text box
            Mouse.Click(uITxtCameraSauEdit, new Point(36, 5));

            // Click 'txtCameraSelfi' text box
            Mouse.Click(uITxtCameraSelfiEdit, new Point(30, 7));

            // Click 'NumericUpDown' text box
            Mouse.Click(uINumericUpDownEdit1, new Point(20, 13));

            // Click 'GB' text box
            Mouse.Click(uIGBEdit, new Point(21, 12));

            // Click 'txtCPU' text box
            Mouse.Click(uITxtCPUEdit, new Point(21, 12));

            // Click 'txtGPU' text box
            Mouse.Click(uITxtGPUEdit, new Point(23, 12));

            // Click 'txtDungLuongPin' text box
            Mouse.Click(uITxtDungLuongPinEdit, new Point(29, 9));

            // Click 'txtTheSim' text box
            Mouse.Click(uITxtTheSimEdit, new Point(21, 13));

            // Click 'txtHeDieuHanh' text box
            Mouse.Click(uITxtHeDieuHanhEdit, new Point(24, 7));

            // Click 'Hoàn tất' button
            Mouse.Click(uIHoàntấtButton, new Point(1, 1));

            // Select 'Tình trạng (Còn hàng)' check box
            uITìnhtrạngCònhàngCheckBox.Checked = this.RecordedMethod1Params.UITìnhtrạngCònhàngCheckBoxChecked;

            // Click 'Thêm mới' button
            Mouse.Click(uIThêmmớiButton, new Point(1, 1));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(62, 24));
        }
        
        /// <summary>
        /// RecordedMethod2 - Use 'RecordedMethod2Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            DXButton uIThêmsảnphẩmButton = this.UISảnphẩmWindow.UIPanelControl1Client.UIThêmsảnphẩmButton;
            WinEdit uITxtTenSPEdit = this.UIThôngtinsảnphẩmWindow.UITxtTenSPWindow.UITxtTenSPEdit;
            WinEdit uITxtXuatSuEdit = this.UIThôngtinsảnphẩmWindow.UITxtXuatSuWindow.UITxtXuatSuEdit;
            WinEdit uINumericUpDownEdit = this.UIThôngtinsảnphẩmWindow.UINumericUpDownSpinner.UINumericUpDownEdit;
            WinDateTimePicker uIPickerNgayCNDateTimePicker = this.UIThôngtinsảnphẩmWindow.UIPickerNgayCNWindow.UIPickerNgayCNDateTimePicker;
            WinCell uIItem29Cell = this.UIItemWindow.UIItemRow.UIItem29Cell;
            WinEdit uITxtDonGiaEdit = this.UIThôngtinsảnphẩmWindow.UITxtDonGiaWindow.UITxtDonGiaEdit;
            WinEdit uITxtHinhMHEdit = this.UIThôngtinsảnphẩmWindow.UITxtHinhMHWindow.UITxtHinhMHEdit;
            WinEdit uITxtGiamGiaEdit = this.UIThôngtinsảnphẩmWindow.UITxtGiamGiaWindow.UITxtGiamGiaEdit;
            WinEdit uITxtDSHinhEdit = this.UIThôngtinsảnphẩmWindow.UITxtDSHinhWindow.UITxtDSHinhEdit;
            WinWindow uITxtKhuyenMaiDiKemWindow = this.UIThôngtinsảnphẩmWindow.UIThôngtinsảnphẩmGroup.UITxtKhuyenMaiDiKemWindow;
            WinEdit uITxtKhuyenMaiDiKemEdit = this.UIThôngtinsảnphẩmWindow.UITxtKhuyenMaiDiKemWindow.UITxtKhuyenMaiDiKemEdit;
            WinEdit uITxtThongTinChiTietEdit = this.UIThôngtinsảnphẩmWindow.UITxtThongTinChiTietWindow.UITxtThongTinChiTietEdit;
            WinEdit uITxtManHinhEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtManHinhWindow.UITxtManHinhEdit;
            WinEdit uITxtCameraSauEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtCameraSauWindow.UITxtCameraSauEdit;
            WinEdit uITxtCameraSelfiEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtCameraSelfiWindow.UITxtCameraSelfiEdit;
            WinEdit uINumericUpDownEdit1 = this.UIThôngtinmôtảchitiếtsWindow.UINumericUpDownSpinner.UINumericUpDownEdit;
            WinEdit uIGBEdit = this.UIThôngtinmôtảchitiếtsWindow.UIGBSpinner.UIGBEdit;
            WinGroup uIThôngtinmôtảsảnphẩmGroup = this.UIThôngtinmôtảchitiếtsWindow.UIThôngtinmôtảsảnphẩmWindow.UIThôngtinmôtảsảnphẩmGroup;
            WinSpinner uIGBSpinner = this.UIThôngtinmôtảchitiếtsWindow.UINumBoNhoTrongWindow.UIGBSpinner;
            WinEdit uITxtCPUEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtCPUWindow.UITxtCPUEdit;
            WinEdit uITxtGPUEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtGPUWindow.UITxtGPUEdit;
            WinEdit uITxtDungLuongPinEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtDungLuongPinWindow.UITxtDungLuongPinEdit;
            WinEdit uITxtTheSimEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtTheSimWindow.UITxtTheSimEdit;
            WinEdit uITxtHeDieuHanhEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtHeDieuHanhWindow.UITxtHeDieuHanhEdit;
            DXButton uIHoàntấtButton = this.UIThôngtinmôtảchitiếtsWindow.UIHoàntấtButton;
            WinCheckBox uITìnhtrạngCònhàngCheckBox = this.UIThôngtinsảnphẩmWindow.UITìnhtrạngCònhàngWindow.UITìnhtrạngCònhàngCheckBox;
            DXButton uIThêmmớiButton = this.UIThôngtinsảnphẩmWindow.UIThêmmớiButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            #endregion

            // Click 'Thêm sản phẩm' button
            Mouse.Click(uIThêmsảnphẩmButton, new Point(1, 1));

            // Type '' in 'txtTenSP' text box
            uITxtTenSPEdit.Text = this.RecordedMethod2Params.UITxtTenSPEditText;

            // Type 'Trung' in 'txtXuatSu' text box
            uITxtXuatSuEdit.Text = this.RecordedMethod2Params.UITxtXuatSuEditText;

            // Click 'NumericUpDown' text box
            Mouse.Click(uINumericUpDownEdit, new Point(134, 16));

            // Click 'pickerNgayCN' date time picker
            Mouse.Click(uIPickerNgayCNDateTimePicker, new Point(171, 4));

            // Click '‎29' cell
            Mouse.Click(uIItem29Cell, new Point(23, 3));

            // Click 'NumericUpDown' text box
            Mouse.Click(uINumericUpDownEdit, new Point(87, 13));

            // Type '12' in 'NumericUpDown' text box
            Keyboard.SendKeys(uINumericUpDownEdit, this.RecordedMethod2Params.UINumericUpDownEditSendKeys, ModifierKeys.None);

            // Type '2345' in 'txtDonGia' text box
            uITxtDonGiaEdit.Text = this.RecordedMethod2Params.UITxtDonGiaEditText;

            // Type 'png' in 'txtHinhMH' text box
            uITxtHinhMHEdit.Text = this.RecordedMethod2Params.UITxtHinhMHEditText;

            // Type '0' in 'txtGiamGia' text box
            uITxtGiamGiaEdit.Text = this.RecordedMethod2Params.UITxtGiamGiaEditText;

            // Type 'png' in 'txtDSHinh' text box
            uITxtDSHinhEdit.Text = this.RecordedMethod2Params.UITxtDSHinhEditText;

            // Click 'txtKhuyenMaiDiKem' window
            Mouse.Click(uITxtKhuyenMaiDiKemWindow, new Point(211, 27));

            // Type '0' in 'txtKhuyenMaiDiKem' text box
            uITxtKhuyenMaiDiKemEdit.Text = this.RecordedMethod2Params.UITxtKhuyenMaiDiKemEditText;

            // Click 'txtThongTinChiTiet' text box
            Mouse.Click(uITxtThongTinChiTietEdit, new Point(177, 44));

            // Type '123' in 'txtManHinh' text box
            uITxtManHinhEdit.Text = this.RecordedMethod2Params.UITxtManHinhEditText;

            // Type 'qư' in 'txtCameraSau' text box
            uITxtCameraSauEdit.Text = this.RecordedMethod2Params.UITxtCameraSauEditText;

            // Type 'e' in 'txtCameraSelfi' text box
            uITxtCameraSelfiEdit.Text = this.RecordedMethod2Params.UITxtCameraSelfiEditText;

            // Click 'NumericUpDown' text box
            Mouse.Click(uINumericUpDownEdit1, new Point(34, 1));

            // Type 'f' in 'NumericUpDown' text box
            Keyboard.SendKeys(uINumericUpDownEdit1, this.RecordedMethod2Params.UINumericUpDownEditSendKeys1, ModifierKeys.None);

            // Click 'GB' text box
            Mouse.Click(uIGBEdit, new Point(67, 8));

            // Click 'Thông tin mô tả sản phẩm' group
            Mouse.Click(uIThôngtinmôtảsảnphẩmGroup, new Point(195, 163));

            // Click 'NumericUpDown' text box
            Mouse.Click(uINumericUpDownEdit1, new Point(82, 6));

            // Type '4' in 'NumericUpDown' text box
            Keyboard.SendKeys(uINumericUpDownEdit1, this.RecordedMethod2Params.UINumericUpDownEditSendKeys2, ModifierKeys.None);

            // Click 'GB' spinner
            Mouse.Click(uIGBSpinner, new Point(70, 0));

            // Click 'GB' text box
            Mouse.Click(uIGBEdit, new Point(66, 3));

            // Type '5' in 'GB' text box
            Keyboard.SendKeys(uIGBEdit, this.RecordedMethod2Params.UIGBEditSendKeys, ModifierKeys.None);

            // Type '45' in 'txtCPU' text box
            uITxtCPUEdit.Text = this.RecordedMethod2Params.UITxtCPUEditText;

            // Type '45' in 'txtGPU' text box
            uITxtGPUEdit.Text = this.RecordedMethod2Params.UITxtGPUEditText;

            // Type 'rr' in 'txtDungLuongPin' text box
            uITxtDungLuongPinEdit.Text = this.RecordedMethod2Params.UITxtDungLuongPinEditText;

            // Type '6' in 'txtTheSim' text box
            uITxtTheSimEdit.Text = this.RecordedMethod2Params.UITxtTheSimEditText;

            // Type 'u' in 'txtHeDieuHanh' text box
            uITxtHeDieuHanhEdit.Text = this.RecordedMethod2Params.UITxtHeDieuHanhEditText;

            // Click 'Hoàn tất' button
            Mouse.Click(uIHoàntấtButton, new Point(1, 1));

            // Select 'Tình trạng (Còn hàng)' check box
            uITìnhtrạngCònhàngCheckBox.Checked = this.RecordedMethod2Params.UITìnhtrạngCònhàngCheckBoxChecked;

            // Click 'Thêm mới' button
            Mouse.Click(uIThêmmớiButton, new Point(1, 1));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(77, 12));
        }
        
        #region Properties
        public virtual RecordedMethod1_ThemThatBaiParams RecordedMethod1_ThemThatBaiParams
        {
            get
            {
                if ((this.mRecordedMethod1_ThemThatBaiParams == null))
                {
                    this.mRecordedMethod1_ThemThatBaiParams = new RecordedMethod1_ThemThatBaiParams();
                }
                return this.mRecordedMethod1_ThemThatBaiParams;
            }
        }
        
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public virtual RecordedMethod2Params RecordedMethod2Params
        {
            get
            {
                if ((this.mRecordedMethod2Params == null))
                {
                    this.mRecordedMethod2Params = new RecordedMethod2Params();
                }
                return this.mRecordedMethod2Params;
            }
        }
        
        public UISảnphẩmWindow UISảnphẩmWindow
        {
            get
            {
                if ((this.mUISảnphẩmWindow == null))
                {
                    this.mUISảnphẩmWindow = new UISảnphẩmWindow();
                }
                return this.mUISảnphẩmWindow;
            }
        }
        
        public UIThôngtinsảnphẩmWindow UIThôngtinsảnphẩmWindow
        {
            get
            {
                if ((this.mUIThôngtinsảnphẩmWindow == null))
                {
                    this.mUIThôngtinsảnphẩmWindow = new UIThôngtinsảnphẩmWindow();
                }
                return this.mUIThôngtinsảnphẩmWindow;
            }
        }
        
        public UITesttxtNotepadWindow UITesttxtNotepadWindow
        {
            get
            {
                if ((this.mUITesttxtNotepadWindow == null))
                {
                    this.mUITesttxtNotepadWindow = new UITesttxtNotepadWindow();
                }
                return this.mUITesttxtNotepadWindow;
            }
        }
        
        public UIThôngtinmôtảchitiếtsWindow UIThôngtinmôtảchitiếtsWindow
        {
            get
            {
                if ((this.mUIThôngtinmôtảchitiếtsWindow == null))
                {
                    this.mUIThôngtinmôtảchitiếtsWindow = new UIThôngtinmôtảchitiếtsWindow();
                }
                return this.mUIThôngtinmôtảchitiếtsWindow;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow();
                }
                return this.mUIOKWindow;
            }
        }
        
        public UIItemWindow1 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow1();
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1_ThemThatBaiParams mRecordedMethod1_ThemThatBaiParams;
        
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private RecordedMethod2Params mRecordedMethod2Params;
        
        private UISảnphẩmWindow mUISảnphẩmWindow;
        
        private UIThôngtinsảnphẩmWindow mUIThôngtinsảnphẩmWindow;
        
        private UITesttxtNotepadWindow mUITesttxtNotepadWindow;
        
        private UIThôngtinmôtảchitiếtsWindow mUIThôngtinmôtảchitiếtsWindow;
        
        private UIOKWindow mUIOKWindow;
        
        private UIItemWindow1 mUIItemWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1_ThemThatBai'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class RecordedMethod1_ThemThatBaiParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Trung Quốc' in 'txtXuatSu' text box
        /// </summary>
        public string UITxtXuatSuEditText = "Trung Quốc";
        
        /// <summary>
        /// Type 'Control + c' in 'Text Editor' text box
        /// </summary>
        public string UITextEditorEditSendKeys = "c";
        
        /// <summary>
        /// Type '29990000' in 'txtDonGia' text box
        /// </summary>
        public string UITxtDonGiaEditText = "29990000";
        
        /// <summary>
        /// Type '120' in 'NumericUpDown' text box
        /// </summary>
        public string UINumericUpDownEditSendKeys = "120";
        
        /// <summary>
        /// Type 'png' in 'txtHinhMH' text box
        /// </summary>
        public string UITxtHinhMHEditText = "png";
        
        /// <summary>
        /// Type '0' in 'txtGiamGia' text box
        /// </summary>
        public string UITxtGiamGiaEditText = "0";
        
        /// <summary>
        /// Type 'png' in 'txtDSHinh' text box
        /// </summary>
        public string UITxtDSHinhEditText = "png";
        
        /// <summary>
        /// Type '0' in 'txtKhuyenMaiDiKem' text box
        /// </summary>
        public string UITxtKhuyenMaiDiKemEditText = "0";
        
        /// <summary>
        /// Type 'Control + c' in 'Text Editor' text box
        /// </summary>
        public string UITextEditorEditSendKeys1 = "c";
        
        /// <summary>
        /// Type '6.7", Super Retina XDR, AMOLED, 2778 x 1284 Pixel' in 'txtManHinh' text box
        /// </summary>
        public string UITxtManHinhEditText = "6.7\", Super Retina XDR, AMOLED, 2778 x 1284 Pixel";
        
        /// <summary>
        /// Type 'Control + c' in 'Text Editor' text box
        /// </summary>
        public string UITextEditorEditSendKeys2 = "c";
        
        /// <summary>
        /// Type '12.0 MP + 12.0' in 'txtCameraSau' text box
        /// </summary>
        public string UITxtCameraSauEditText = "12.0 MP + 12.0";
        
        /// <summary>
        /// Type 'Control + c' in 'Text Editor' text box
        /// </summary>
        public string UITextEditorEditSendKeys3 = "c";
        
        /// <summary>
        /// Type '{LMenu}' in 'Text Editor' text box
        /// </summary>
        public string UITextEditorEditSendKeys4 = "{LMenu}";
        
        /// <summary>
        /// Type 'Control + v' in 'GB' text box
        /// </summary>
        public string UIGBEditSendKeys = "v";
        
        /// <summary>
        /// Type '128' in 'GB' text box
        /// </summary>
        public string UIGBEditSendKeys1 = "128";
        
        /// <summary>
        /// Type '6' in 'NumericUpDown' text box
        /// </summary>
        public string UINumericUpDownEditSendKeys1 = "6";
        
        /// <summary>
        /// Type 'Control + c' in 'Text Editor' text box
        /// </summary>
        public string UITextEditorEditSendKeys5 = "c";
        
        /// <summary>
        /// Type '12.0 MP' in 'txtCameraSelfi' text box
        /// </summary>
        public string UITxtCameraSelfiEditText = "12.0 MP";
        
        /// <summary>
        /// Type 'Control + c' in 'Text Editor' text box
        /// </summary>
        public string UITextEditorEditSendKeys6 = "c";
        
        /// <summary>
        /// Type 'A14 Bionic' in 'txtCPU' text box
        /// </summary>
        public string UITxtCPUEditText = "A14 Bionic";
        
        /// <summary>
        /// Type 'Control + c' in 'Text Editor' text box
        /// </summary>
        public string UITextEditorEditSendKeys7 = "c";
        
        /// <summary>
        /// Type 'Apple GPU 4 nhân' in 'txtGPU' text box
        /// </summary>
        public string UITxtGPUEditText = "Apple GPU 4 nhân";
        
        /// <summary>
        /// Type 'Control + c' in 'Text Editor' text box
        /// </summary>
        public string UITextEditorEditSendKeys8 = "c";
        
        /// <summary>
        /// Type '3687 mAh' in 'txtDungLuongPin' text box
        /// </summary>
        public string UITxtDungLuongPinEditText = "3687 mAh";
        
        /// <summary>
        /// Type 'Control + c' in 'Text Editor' text box
        /// </summary>
        public string UITextEditorEditSendKeys9 = "c";
        
        /// <summary>
        /// Type '1 eSIM, 1 Nano SIM' in 'txtTheSim' text box
        /// </summary>
        public string UITxtTheSimEditText = "1 eSIM, 1 Nano SIM";
        
        /// <summary>
        /// Type 'Control + c' in 'Text Editor' text box
        /// </summary>
        public string UITextEditorEditSendKeys10 = "c";
        
        /// <summary>
        /// Type 'iOS 14' in 'txtHeDieuHanh' text box
        /// </summary>
        public string UITxtHeDieuHanhEditText = "iOS 14";
        
        /// <summary>
        /// Select 'Tình trạng (Còn hàng)' check box
        /// </summary>
        public bool UITìnhtrạngCònhàngCheckBoxChecked = true;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Select 'Tình trạng (Còn hàng)' check box
        /// </summary>
        public bool UITìnhtrạngCònhàngCheckBoxChecked = true;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class RecordedMethod2Params
    {
        
        #region Fields
        /// <summary>
        /// Type '' in 'txtTenSP' text box
        /// </summary>
        public string UITxtTenSPEditText = "";
        
        /// <summary>
        /// Type 'Trung' in 'txtXuatSu' text box
        /// </summary>
        public string UITxtXuatSuEditText = "Trung";
        
        /// <summary>
        /// Type '12' in 'NumericUpDown' text box
        /// </summary>
        public string UINumericUpDownEditSendKeys = "12";
        
        /// <summary>
        /// Type '2345' in 'txtDonGia' text box
        /// </summary>
        public string UITxtDonGiaEditText = "2345";
        
        /// <summary>
        /// Type 'png' in 'txtHinhMH' text box
        /// </summary>
        public string UITxtHinhMHEditText = "png";
        
        /// <summary>
        /// Type '0' in 'txtGiamGia' text box
        /// </summary>
        public string UITxtGiamGiaEditText = "0";
        
        /// <summary>
        /// Type 'png' in 'txtDSHinh' text box
        /// </summary>
        public string UITxtDSHinhEditText = "png";
        
        /// <summary>
        /// Type '0' in 'txtKhuyenMaiDiKem' text box
        /// </summary>
        public string UITxtKhuyenMaiDiKemEditText = "0";
        
        /// <summary>
        /// Type '123' in 'txtManHinh' text box
        /// </summary>
        public string UITxtManHinhEditText = "123";
        
        /// <summary>
        /// Type 'qư' in 'txtCameraSau' text box
        /// </summary>
        public string UITxtCameraSauEditText = "qư";
        
        /// <summary>
        /// Type 'e' in 'txtCameraSelfi' text box
        /// </summary>
        public string UITxtCameraSelfiEditText = "e";
        
        /// <summary>
        /// Type 'f' in 'NumericUpDown' text box
        /// </summary>
        public string UINumericUpDownEditSendKeys1 = "f";
        
        /// <summary>
        /// Type '4' in 'NumericUpDown' text box
        /// </summary>
        public string UINumericUpDownEditSendKeys2 = "4";
        
        /// <summary>
        /// Type '5' in 'GB' text box
        /// </summary>
        public string UIGBEditSendKeys = "5";
        
        /// <summary>
        /// Type '45' in 'txtCPU' text box
        /// </summary>
        public string UITxtCPUEditText = "45";
        
        /// <summary>
        /// Type '45' in 'txtGPU' text box
        /// </summary>
        public string UITxtGPUEditText = "45";
        
        /// <summary>
        /// Type 'rr' in 'txtDungLuongPin' text box
        /// </summary>
        public string UITxtDungLuongPinEditText = "rr";
        
        /// <summary>
        /// Type '6' in 'txtTheSim' text box
        /// </summary>
        public string UITxtTheSimEditText = "6";
        
        /// <summary>
        /// Type 'u' in 'txtHeDieuHanh' text box
        /// </summary>
        public string UITxtHeDieuHanhEditText = "u";
        
        /// <summary>
        /// Select 'Tình trạng (Còn hàng)' check box
        /// </summary>
        public bool UITìnhtrạngCònhàngCheckBoxChecked = true;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UISảnphẩmWindow : WinWindow
    {
        
        public UISảnphẩmWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Sản phẩm";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Sản phẩm");
            #endregion
        }
        
        #region Properties
        public UIPanelControl1Client UIPanelControl1Client
        {
            get
            {
                if ((this.mUIPanelControl1Client == null))
                {
                    this.mUIPanelControl1Client = new UIPanelControl1Client(this);
                }
                return this.mUIPanelControl1Client;
            }
        }
        #endregion
        
        #region Fields
        private UIPanelControl1Client mUIPanelControl1Client;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIPanelControl1Client : DXTestControl
    {
        
        public UIPanelControl1Client(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = "panelControl1";
            this.SearchProperties[DXTestControl.PropertyNames.ClassName] = "PanelControl";
            this.WindowTitles.Add("Sản phẩm");
            #endregion
        }
        
        #region Properties
        public DXButton UIThêmsảnphẩmButton
        {
            get
            {
                if ((this.mUIThêmsảnphẩmButton == null))
                {
                    this.mUIThêmsảnphẩmButton = new DXButton(this);
                    #region Search Criteria
                    this.mUIThêmsảnphẩmButton.SearchProperties[DXTestControl.PropertyNames.Name] = "btnThemSP";
                    this.mUIThêmsảnphẩmButton.SearchProperties[DXTestControl.PropertyNames.ClassName] = "ButtonDesign";
                    this.mUIThêmsảnphẩmButton.WindowTitles.Add("Sản phẩm");
                    #endregion
                }
                return this.mUIThêmsảnphẩmButton;
            }
        }
        #endregion
        
        #region Fields
        private DXButton mUIThêmsảnphẩmButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIThôngtinsảnphẩmWindow : WinWindow
    {
        
        public UIThôngtinsảnphẩmWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Thông tin sản phẩm";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public UITxtTenSPWindow UITxtTenSPWindow
        {
            get
            {
                if ((this.mUITxtTenSPWindow == null))
                {
                    this.mUITxtTenSPWindow = new UITxtTenSPWindow(this);
                }
                return this.mUITxtTenSPWindow;
            }
        }
        
        public UITxtXuatSuWindow UITxtXuatSuWindow
        {
            get
            {
                if ((this.mUITxtXuatSuWindow == null))
                {
                    this.mUITxtXuatSuWindow = new UITxtXuatSuWindow(this);
                }
                return this.mUITxtXuatSuWindow;
            }
        }
        
        public UITxtDonGiaWindow UITxtDonGiaWindow
        {
            get
            {
                if ((this.mUITxtDonGiaWindow == null))
                {
                    this.mUITxtDonGiaWindow = new UITxtDonGiaWindow(this);
                }
                return this.mUITxtDonGiaWindow;
            }
        }
        
        public UINumericUpDownSpinner UINumericUpDownSpinner
        {
            get
            {
                if ((this.mUINumericUpDownSpinner == null))
                {
                    this.mUINumericUpDownSpinner = new UINumericUpDownSpinner(this);
                }
                return this.mUINumericUpDownSpinner;
            }
        }
        
        public UITxtHinhMHWindow UITxtHinhMHWindow
        {
            get
            {
                if ((this.mUITxtHinhMHWindow == null))
                {
                    this.mUITxtHinhMHWindow = new UITxtHinhMHWindow(this);
                }
                return this.mUITxtHinhMHWindow;
            }
        }
        
        public UITxtGiamGiaWindow UITxtGiamGiaWindow
        {
            get
            {
                if ((this.mUITxtGiamGiaWindow == null))
                {
                    this.mUITxtGiamGiaWindow = new UITxtGiamGiaWindow(this);
                }
                return this.mUITxtGiamGiaWindow;
            }
        }
        
        public UITxtDSHinhWindow UITxtDSHinhWindow
        {
            get
            {
                if ((this.mUITxtDSHinhWindow == null))
                {
                    this.mUITxtDSHinhWindow = new UITxtDSHinhWindow(this);
                }
                return this.mUITxtDSHinhWindow;
            }
        }
        
        public UITxtKhuyenMaiDiKemWindow UITxtKhuyenMaiDiKemWindow
        {
            get
            {
                if ((this.mUITxtKhuyenMaiDiKemWindow == null))
                {
                    this.mUITxtKhuyenMaiDiKemWindow = new UITxtKhuyenMaiDiKemWindow(this);
                }
                return this.mUITxtKhuyenMaiDiKemWindow;
            }
        }
        
        public UITxtThongTinChiTietWindow UITxtThongTinChiTietWindow
        {
            get
            {
                if ((this.mUITxtThongTinChiTietWindow == null))
                {
                    this.mUITxtThongTinChiTietWindow = new UITxtThongTinChiTietWindow(this);
                }
                return this.mUITxtThongTinChiTietWindow;
            }
        }
        
        public UITìnhtrạngCònhàngWindow UITìnhtrạngCònhàngWindow
        {
            get
            {
                if ((this.mUITìnhtrạngCònhàngWindow == null))
                {
                    this.mUITìnhtrạngCònhàngWindow = new UITìnhtrạngCònhàngWindow(this);
                }
                return this.mUITìnhtrạngCònhàngWindow;
            }
        }
        
        public DXButton UIThêmmớiButton
        {
            get
            {
                if ((this.mUIThêmmớiButton == null))
                {
                    this.mUIThêmmớiButton = new DXButton(this);
                    #region Search Criteria
                    this.mUIThêmmớiButton.SearchProperties[DXTestControl.PropertyNames.Name] = "btnThemMoi";
                    this.mUIThêmmớiButton.SearchProperties[DXTestControl.PropertyNames.ClassName] = "ButtonDesign";
                    this.mUIThêmmớiButton.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUIThêmmớiButton;
            }
        }
        
        public UIPickerNgayCNWindow UIPickerNgayCNWindow
        {
            get
            {
                if ((this.mUIPickerNgayCNWindow == null))
                {
                    this.mUIPickerNgayCNWindow = new UIPickerNgayCNWindow(this);
                }
                return this.mUIPickerNgayCNWindow;
            }
        }
        
        public UIThôngtinsảnphẩmGroup UIThôngtinsảnphẩmGroup
        {
            get
            {
                if ((this.mUIThôngtinsảnphẩmGroup == null))
                {
                    this.mUIThôngtinsảnphẩmGroup = new UIThôngtinsảnphẩmGroup(this);
                }
                return this.mUIThôngtinsảnphẩmGroup;
            }
        }
        #endregion
        
        #region Fields
        private UITxtTenSPWindow mUITxtTenSPWindow;
        
        private UITxtXuatSuWindow mUITxtXuatSuWindow;
        
        private UITxtDonGiaWindow mUITxtDonGiaWindow;
        
        private UINumericUpDownSpinner mUINumericUpDownSpinner;
        
        private UITxtHinhMHWindow mUITxtHinhMHWindow;
        
        private UITxtGiamGiaWindow mUITxtGiamGiaWindow;
        
        private UITxtDSHinhWindow mUITxtDSHinhWindow;
        
        private UITxtKhuyenMaiDiKemWindow mUITxtKhuyenMaiDiKemWindow;
        
        private UITxtThongTinChiTietWindow mUITxtThongTinChiTietWindow;
        
        private UITìnhtrạngCònhàngWindow mUITìnhtrạngCònhàngWindow;
        
        private DXButton mUIThêmmớiButton;
        
        private UIPickerNgayCNWindow mUIPickerNgayCNWindow;
        
        private UIThôngtinsảnphẩmGroup mUIThôngtinsảnphẩmGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtTenSPWindow : WinWindow
    {
        
        public UITxtTenSPWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtTenSP";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtTenSPEdit
        {
            get
            {
                if ((this.mUITxtTenSPEdit == null))
                {
                    this.mUITxtTenSPEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtTenSPEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Tên sản phẩm:";
                    this.mUITxtTenSPEdit.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtTenSPEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtTenSPEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtXuatSuWindow : WinWindow
    {
        
        public UITxtXuatSuWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtXuatSu";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtXuatSuEdit
        {
            get
            {
                if ((this.mUITxtXuatSuEdit == null))
                {
                    this.mUITxtXuatSuEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtXuatSuEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Xuất sứ:";
                    this.mUITxtXuatSuEdit.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtXuatSuEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtXuatSuEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtDonGiaWindow : WinWindow
    {
        
        public UITxtDonGiaWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtDonGia";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtDonGiaEdit
        {
            get
            {
                if ((this.mUITxtDonGiaEdit == null))
                {
                    this.mUITxtDonGiaEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtDonGiaEdit.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtDonGiaEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtDonGiaEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UINumericUpDownSpinner : WinSpinner
    {
        
        public UINumericUpDownSpinner(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinSpinner.PropertyNames.Name] = "NumericUpDown";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UINumericUpDownEdit
        {
            get
            {
                if ((this.mUINumericUpDownEdit == null))
                {
                    this.mUINumericUpDownEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUINumericUpDownEdit.SearchProperties[WinEdit.PropertyNames.Name] = "NumericUpDown";
                    this.mUINumericUpDownEdit.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUINumericUpDownEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINumericUpDownEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtHinhMHWindow : WinWindow
    {
        
        public UITxtHinhMHWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtHinhMH";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtHinhMHEdit
        {
            get
            {
                if ((this.mUITxtHinhMHEdit == null))
                {
                    this.mUITxtHinhMHEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtHinhMHEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Giảm giá:";
                    this.mUITxtHinhMHEdit.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtHinhMHEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtHinhMHEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtGiamGiaWindow : WinWindow
    {
        
        public UITxtGiamGiaWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtGiamGia";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtGiamGiaEdit
        {
            get
            {
                if ((this.mUITxtGiamGiaEdit == null))
                {
                    this.mUITxtGiamGiaEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtGiamGiaEdit.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtGiamGiaEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtGiamGiaEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtDSHinhWindow : WinWindow
    {
        
        public UITxtDSHinhWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtDSHinh";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtDSHinhEdit
        {
            get
            {
                if ((this.mUITxtDSHinhEdit == null))
                {
                    this.mUITxtDSHinhEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtDSHinhEdit.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtDSHinhEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtDSHinhEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtKhuyenMaiDiKemWindow : WinWindow
    {
        
        public UITxtKhuyenMaiDiKemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtKhuyenMaiDiKem";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtKhuyenMaiDiKemEdit
        {
            get
            {
                if ((this.mUITxtKhuyenMaiDiKemEdit == null))
                {
                    this.mUITxtKhuyenMaiDiKemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtKhuyenMaiDiKemEdit.SearchProperties[WinEdit.PropertyNames.Name] = "K/Mãi đi kèm:";
                    this.mUITxtKhuyenMaiDiKemEdit.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtKhuyenMaiDiKemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtKhuyenMaiDiKemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtThongTinChiTietWindow : WinWindow
    {
        
        public UITxtThongTinChiTietWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtThongTinChiTiet";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtThongTinChiTietEdit
        {
            get
            {
                if ((this.mUITxtThongTinChiTietEdit == null))
                {
                    this.mUITxtThongTinChiTietEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtThongTinChiTietEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Thông tin chi tiết:";
                    this.mUITxtThongTinChiTietEdit.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtThongTinChiTietEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtThongTinChiTietEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITìnhtrạngCònhàngWindow : WinWindow
    {
        
        public UITìnhtrạngCònhàngWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "ckbTinhTrang";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinCheckBox UITìnhtrạngCònhàngCheckBox
        {
            get
            {
                if ((this.mUITìnhtrạngCònhàngCheckBox == null))
                {
                    this.mUITìnhtrạngCònhàngCheckBox = new WinCheckBox(this);
                    #region Search Criteria
                    this.mUITìnhtrạngCònhàngCheckBox.SearchProperties[WinCheckBox.PropertyNames.Name] = "Tình trạng (Còn hàng)";
                    this.mUITìnhtrạngCònhàngCheckBox.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITìnhtrạngCònhàngCheckBox;
            }
        }
        #endregion
        
        #region Fields
        private WinCheckBox mUITìnhtrạngCònhàngCheckBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIPickerNgayCNWindow : WinWindow
    {
        
        public UIPickerNgayCNWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "pickerNgayCN";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinDateTimePicker UIPickerNgayCNDateTimePicker
        {
            get
            {
                if ((this.mUIPickerNgayCNDateTimePicker == null))
                {
                    this.mUIPickerNgayCNDateTimePicker = new WinDateTimePicker(this);
                    #region Search Criteria
                    this.mUIPickerNgayCNDateTimePicker.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUIPickerNgayCNDateTimePicker;
            }
        }
        #endregion
        
        #region Fields
        private WinDateTimePicker mUIPickerNgayCNDateTimePicker;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIThôngtinsảnphẩmGroup : WinGroup
    {
        
        public UIThôngtinsảnphẩmGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Thông tin sản phẩm";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinWindow UITxtKhuyenMaiDiKemWindow
        {
            get
            {
                if ((this.mUITxtKhuyenMaiDiKemWindow == null))
                {
                    this.mUITxtKhuyenMaiDiKemWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtKhuyenMaiDiKemWindow.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "K/Mãi đi kèm:";
                    this.mUITxtKhuyenMaiDiKemWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtKhuyenMaiDiKemWindow.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtKhuyenMaiDiKemWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUITxtKhuyenMaiDiKemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITesttxtNotepadWindow : WinWindow
    {
        
        public UITesttxtNotepadWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "test.txt - Notepad";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Notepad";
            this.WindowTitles.Add("test.txt - Notepad");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "15";
            this.WindowTitles.Add("test.txt - Notepad");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextEditorEdit
        {
            get
            {
                if ((this.mUITextEditorEdit == null))
                {
                    this.mUITextEditorEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITextEditorEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Text Editor";
                    this.mUITextEditorEdit.WindowTitles.Add("test.txt - Notepad");
                    #endregion
                }
                return this.mUITextEditorEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextEditorEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIThôngtinmôtảchitiếtsWindow : WinWindow
    {
        
        public UIThôngtinmôtảchitiếtsWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Thông tin mô tả chi tiết sản phẩm";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public UIThôngtinmôtảsảnphẩmWindow UIThôngtinmôtảsảnphẩmWindow
        {
            get
            {
                if ((this.mUIThôngtinmôtảsảnphẩmWindow == null))
                {
                    this.mUIThôngtinmôtảsảnphẩmWindow = new UIThôngtinmôtảsảnphẩmWindow(this);
                }
                return this.mUIThôngtinmôtảsảnphẩmWindow;
            }
        }
        
        public UITxtManHinhWindow UITxtManHinhWindow
        {
            get
            {
                if ((this.mUITxtManHinhWindow == null))
                {
                    this.mUITxtManHinhWindow = new UITxtManHinhWindow(this);
                }
                return this.mUITxtManHinhWindow;
            }
        }
        
        public UITxtCameraSauWindow UITxtCameraSauWindow
        {
            get
            {
                if ((this.mUITxtCameraSauWindow == null))
                {
                    this.mUITxtCameraSauWindow = new UITxtCameraSauWindow(this);
                }
                return this.mUITxtCameraSauWindow;
            }
        }
        
        public UIGBSpinner UIGBSpinner
        {
            get
            {
                if ((this.mUIGBSpinner == null))
                {
                    this.mUIGBSpinner = new UIGBSpinner(this);
                }
                return this.mUIGBSpinner;
            }
        }
        
        public UINumRAMWindow UINumRAMWindow
        {
            get
            {
                if ((this.mUINumRAMWindow == null))
                {
                    this.mUINumRAMWindow = new UINumRAMWindow(this);
                }
                return this.mUINumRAMWindow;
            }
        }
        
        public UINumericUpDownSpinner1 UINumericUpDownSpinner
        {
            get
            {
                if ((this.mUINumericUpDownSpinner == null))
                {
                    this.mUINumericUpDownSpinner = new UINumericUpDownSpinner1(this);
                }
                return this.mUINumericUpDownSpinner;
            }
        }
        
        public UITxtCameraSelfiWindow UITxtCameraSelfiWindow
        {
            get
            {
                if ((this.mUITxtCameraSelfiWindow == null))
                {
                    this.mUITxtCameraSelfiWindow = new UITxtCameraSelfiWindow(this);
                }
                return this.mUITxtCameraSelfiWindow;
            }
        }
        
        public UITxtCPUWindow UITxtCPUWindow
        {
            get
            {
                if ((this.mUITxtCPUWindow == null))
                {
                    this.mUITxtCPUWindow = new UITxtCPUWindow(this);
                }
                return this.mUITxtCPUWindow;
            }
        }
        
        public UITxtGPUWindow UITxtGPUWindow
        {
            get
            {
                if ((this.mUITxtGPUWindow == null))
                {
                    this.mUITxtGPUWindow = new UITxtGPUWindow(this);
                }
                return this.mUITxtGPUWindow;
            }
        }
        
        public UITxtDungLuongPinWindow UITxtDungLuongPinWindow
        {
            get
            {
                if ((this.mUITxtDungLuongPinWindow == null))
                {
                    this.mUITxtDungLuongPinWindow = new UITxtDungLuongPinWindow(this);
                }
                return this.mUITxtDungLuongPinWindow;
            }
        }
        
        public UITxtTheSimWindow UITxtTheSimWindow
        {
            get
            {
                if ((this.mUITxtTheSimWindow == null))
                {
                    this.mUITxtTheSimWindow = new UITxtTheSimWindow(this);
                }
                return this.mUITxtTheSimWindow;
            }
        }
        
        public UITxtHeDieuHanhWindow UITxtHeDieuHanhWindow
        {
            get
            {
                if ((this.mUITxtHeDieuHanhWindow == null))
                {
                    this.mUITxtHeDieuHanhWindow = new UITxtHeDieuHanhWindow(this);
                }
                return this.mUITxtHeDieuHanhWindow;
            }
        }
        
        public DXButton UIHoàntấtButton
        {
            get
            {
                if ((this.mUIHoàntấtButton == null))
                {
                    this.mUIHoàntấtButton = new DXButton(this);
                    #region Search Criteria
                    this.mUIHoàntấtButton.SearchProperties[DXTestControl.PropertyNames.Name] = "btnHoatTat";
                    this.mUIHoàntấtButton.SearchProperties[DXTestControl.PropertyNames.ClassName] = "ButtonDesign";
                    this.mUIHoàntấtButton.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUIHoàntấtButton;
            }
        }
        
        public UINumBoNhoTrongWindow UINumBoNhoTrongWindow
        {
            get
            {
                if ((this.mUINumBoNhoTrongWindow == null))
                {
                    this.mUINumBoNhoTrongWindow = new UINumBoNhoTrongWindow(this);
                }
                return this.mUINumBoNhoTrongWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIThôngtinmôtảsảnphẩmWindow mUIThôngtinmôtảsảnphẩmWindow;
        
        private UITxtManHinhWindow mUITxtManHinhWindow;
        
        private UITxtCameraSauWindow mUITxtCameraSauWindow;
        
        private UIGBSpinner mUIGBSpinner;
        
        private UINumRAMWindow mUINumRAMWindow;
        
        private UINumericUpDownSpinner1 mUINumericUpDownSpinner;
        
        private UITxtCameraSelfiWindow mUITxtCameraSelfiWindow;
        
        private UITxtCPUWindow mUITxtCPUWindow;
        
        private UITxtGPUWindow mUITxtGPUWindow;
        
        private UITxtDungLuongPinWindow mUITxtDungLuongPinWindow;
        
        private UITxtTheSimWindow mUITxtTheSimWindow;
        
        private UITxtHeDieuHanhWindow mUITxtHeDieuHanhWindow;
        
        private DXButton mUIHoàntấtButton;
        
        private UINumBoNhoTrongWindow mUINumBoNhoTrongWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIThôngtinmôtảsảnphẩmWindow : WinWindow
    {
        
        public UIThôngtinmôtảsảnphẩmWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "groupBox1";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinGroup UIThôngtinmôtảsảnphẩmGroup
        {
            get
            {
                if ((this.mUIThôngtinmôtảsảnphẩmGroup == null))
                {
                    this.mUIThôngtinmôtảsảnphẩmGroup = new WinGroup(this);
                    #region Search Criteria
                    this.mUIThôngtinmôtảsảnphẩmGroup.SearchProperties[WinControl.PropertyNames.Name] = "Thông tin mô tả sản phẩm";
                    this.mUIThôngtinmôtảsảnphẩmGroup.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUIThôngtinmôtảsảnphẩmGroup;
            }
        }
        #endregion
        
        #region Fields
        private WinGroup mUIThôngtinmôtảsảnphẩmGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtManHinhWindow : WinWindow
    {
        
        public UITxtManHinhWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtManHinh";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtManHinhEdit
        {
            get
            {
                if ((this.mUITxtManHinhEdit == null))
                {
                    this.mUITxtManHinhEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtManHinhEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtManHinhEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtManHinhEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtCameraSauWindow : WinWindow
    {
        
        public UITxtCameraSauWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtCameraSau";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtCameraSauEdit
        {
            get
            {
                if ((this.mUITxtCameraSauEdit == null))
                {
                    this.mUITxtCameraSauEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtCameraSauEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtCameraSauEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtCameraSauEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIGBSpinner : WinSpinner
    {
        
        public UIGBSpinner(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinSpinner.PropertyNames.Name] = "GB";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UIGBEdit
        {
            get
            {
                if ((this.mUIGBEdit == null))
                {
                    this.mUIGBEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIGBEdit.SearchProperties[WinEdit.PropertyNames.Name] = "GB";
                    this.mUIGBEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUIGBEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIGBEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UINumRAMWindow : WinWindow
    {
        
        public UINumRAMWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "numRAM";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinSpinner UINumericUpDownSpinner
        {
            get
            {
                if ((this.mUINumericUpDownSpinner == null))
                {
                    this.mUINumericUpDownSpinner = new WinSpinner(this);
                    #region Search Criteria
                    this.mUINumericUpDownSpinner.SearchProperties[WinSpinner.PropertyNames.Name] = "NumericUpDown";
                    this.mUINumericUpDownSpinner.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUINumericUpDownSpinner;
            }
        }
        #endregion
        
        #region Fields
        private WinSpinner mUINumericUpDownSpinner;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UINumericUpDownSpinner1 : WinSpinner
    {
        
        public UINumericUpDownSpinner1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinSpinner.PropertyNames.Name] = "NumericUpDown";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UINumericUpDownEdit
        {
            get
            {
                if ((this.mUINumericUpDownEdit == null))
                {
                    this.mUINumericUpDownEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUINumericUpDownEdit.SearchProperties[WinEdit.PropertyNames.Name] = "NumericUpDown";
                    this.mUINumericUpDownEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUINumericUpDownEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINumericUpDownEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtCameraSelfiWindow : WinWindow
    {
        
        public UITxtCameraSelfiWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtCameraSelfi";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtCameraSelfiEdit
        {
            get
            {
                if ((this.mUITxtCameraSelfiEdit == null))
                {
                    this.mUITxtCameraSelfiEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtCameraSelfiEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Màn hình:";
                    this.mUITxtCameraSelfiEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtCameraSelfiEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtCameraSelfiEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtCPUWindow : WinWindow
    {
        
        public UITxtCPUWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtCPU";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtCPUEdit
        {
            get
            {
                if ((this.mUITxtCPUEdit == null))
                {
                    this.mUITxtCPUEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtCPUEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtCPUEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtCPUEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtGPUWindow : WinWindow
    {
        
        public UITxtGPUWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtGPU";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtGPUEdit
        {
            get
            {
                if ((this.mUITxtGPUEdit == null))
                {
                    this.mUITxtGPUEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtGPUEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtGPUEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtGPUEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtDungLuongPinWindow : WinWindow
    {
        
        public UITxtDungLuongPinWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtDungLuongPin";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtDungLuongPinEdit
        {
            get
            {
                if ((this.mUITxtDungLuongPinEdit == null))
                {
                    this.mUITxtDungLuongPinEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtDungLuongPinEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtDungLuongPinEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtDungLuongPinEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtTheSimWindow : WinWindow
    {
        
        public UITxtTheSimWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtTheSim";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtTheSimEdit
        {
            get
            {
                if ((this.mUITxtTheSimEdit == null))
                {
                    this.mUITxtTheSimEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtTheSimEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtTheSimEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtTheSimEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtHeDieuHanhWindow : WinWindow
    {
        
        public UITxtHeDieuHanhWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtHeDieuHanh";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtHeDieuHanhEdit
        {
            get
            {
                if ((this.mUITxtHeDieuHanhEdit == null))
                {
                    this.mUITxtHeDieuHanhEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtHeDieuHanhEdit.SearchProperties[WinEdit.PropertyNames.Name] = "CPU:";
                    this.mUITxtHeDieuHanhEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtHeDieuHanhEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtHeDieuHanhEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UINumBoNhoTrongWindow : WinWindow
    {
        
        public UINumBoNhoTrongWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "numBoNhoTrong";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinSpinner UIGBSpinner
        {
            get
            {
                if ((this.mUIGBSpinner == null))
                {
                    this.mUIGBSpinner = new WinSpinner(this);
                    #region Search Criteria
                    this.mUIGBSpinner.SearchProperties[WinSpinner.PropertyNames.Name] = "GB";
                    this.mUIGBSpinner.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUIGBSpinner;
            }
        }
        #endregion
        
        #region Fields
        private WinSpinner mUIGBSpinner;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "OK";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("OK");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("OK");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Calendar Control";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "SysMonthCal32";
            #endregion
        }
        
        #region Properties
        public UIItemRow UIItemRow
        {
            get
            {
                if ((this.mUIItemRow == null))
                {
                    this.mUIItemRow = new UIItemRow(this);
                }
                return this.mUIItemRow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemRow mUIItemRow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIItemRow : WinRow
    {
        
        public UIItemRow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            #endregion
        }
        
        #region Properties
        public WinCell UIItem29Cell
        {
            get
            {
                if ((this.mUIItem29Cell == null))
                {
                    this.mUIItem29Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem29Cell.SearchProperties[WinCell.PropertyNames.Name] = "‎29";
                    #endregion
                }
                return this.mUIItem29Cell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUIItem29Cell;
        #endregion
    }
}
