// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 16.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Testfrm
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using DevExpress.CodedUIExtension.DXTestControls.v19_2;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            DXButton uIThêmsảnphẩmButton = this.UISảnphẩmWindow.UIThêmsảnphẩmButton;
            WinEdit uITxtProductNameEdit = this.UIThôngtinsảnphẩmWindow.UITxtProductNameWindow.UITxtProductNameEdit;
            WinEdit uITxtMadeInEdit = this.UIThôngtinsảnphẩmWindow.UITxtMadeInWindow.UITxtMadeInEdit;
            WinEdit uITxtUnitPriceImportEdit = this.UIThôngtinsảnphẩmWindow.UITxtUnitPriceImportWindow.UITxtUnitPriceImportEdit;
            DXButton uIBtnChoseImagesButton = this.UIThôngtinsảnphẩmWindow.UIBtnChoseImagesButton;
            WinListItem uIIphone12promaxxamnewListItem = this.UIOpenWindow.UIItemWindow.UIItemsViewList.UIIphone12promaxxamnewListItem;
            WinWindow uIBtnChoseListImagesWindow = this.UIThôngtinsảnphẩmWindow.UIThôngtinsảnphẩmGroup.UIBtnChoseListImagesWindow;
            DXButton uIBtnChoseListImagesButton = this.UIThôngtinsảnphẩmWindow.UIBtnChoseListImagesButton;
            WinEdit uITxtProductDetailsEdit = this.UIThôngtinsảnphẩmWindow.UITxtProductDetailsWindow.UITxtProductDetailsEdit;
            WinEdit uITxtScreenEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtScreenWindow.UITxtScreenEdit;
            WinEdit uITxtRearCameraEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtRearCameraWindow.UITxtRearCameraEdit;
            WinEdit uITxtCameraSelfieEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtCameraSelfieWindow.UITxtCameraSelfieEdit;
            WinEdit uINumericUpDownEdit = this.UIThôngtinmôtảchitiếtsWindow.UINumericUpDownSpinner.UINumericUpDownEdit;
            WinEdit uICPUEdit = this.UIThôngtinmôtảchitiếtsWindow.UICPUSpinner.UICPUEdit;
            WinEdit uITxtCPUEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtCPUWindow.UITxtCPUEdit;
            WinEdit uITxtGPUEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtGPUWindow.UITxtGPUEdit;
            WinEdit uITxtBatteriesEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtBatteriesWindow.UITxtBatteriesEdit;
            WinEdit uITxtSimEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtSimWindow.UITxtSimEdit;
            WinEdit uITxtOparatingSystemEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtOparatingSystemWindow.UITxtOparatingSystemEdit;
            DXButton uIHoàntấtButton = this.UIThôngtinmôtảchitiếtsWindow.UIHoàntấtButton;
            DXButton uIThêmmớiButton = this.UIThôngtinsảnphẩmWindow.UIThêmmớiButton;
            DXButton uIOKButton = this.UIItemWindow.UIThôngbáoWindow.UIOKButton;
            #endregion

            // Click 'Thêm sản phẩm' button
            Mouse.Click(uIThêmsảnphẩmButton, new Point(1, 1));

            // Click 'Thêm sản phẩm' button
            Mouse.Click(uIThêmsảnphẩmButton, new Point(1, 1));

            // Type 'a' in 'txtProductName' text box
            uITxtProductNameEdit.Text = this.RecordedMethod1Params.UITxtProductNameEditText;

            // Type 'a' in 'txtMadeIn' text box
            uITxtMadeInEdit.Text = this.RecordedMethod1Params.UITxtMadeInEditText;

            // Type '12' in 'txtUnitPriceImport' text box
            uITxtUnitPriceImportEdit.Text = this.RecordedMethod1Params.UITxtUnitPriceImportEditText;

            // Click 'btnChoseImages' button
            Mouse.Click(uIBtnChoseImagesButton, new Point(1, 1));

            // Double-Click 'iphone-12-pro-max-xam-new-600x600-200x200.jpg' list item
            Mouse.DoubleClick(uIIphone12promaxxamnewListItem, new Point(66, 86));

            // Click 'btnChoseListImages' window
            Mouse.Click(uIBtnChoseListImagesWindow, new Point(23, 27));

            // Click 'btnChoseListImages' button
            Mouse.Click(uIBtnChoseListImagesButton, new Point(1, 1));

            // Double-Click 'iphone-12-pro-max-xam-new-600x600-200x200.jpg' list item
            Mouse.DoubleClick(uIIphone12promaxxamnewListItem, new Point(60, 75));

            // Click 'txtProductDetails' text box
            Mouse.Click(uITxtProductDetailsEdit, new Point(384, 73));

            // Type 'a' in 'txtScreen' text box
            uITxtScreenEdit.Text = this.RecordedMethod1Params.UITxtScreenEditText;

            // Type '2' in 'txtRearCamera' text box
            uITxtRearCameraEdit.Text = this.RecordedMethod1Params.UITxtRearCameraEditText;

            // Last mouse action was not recorded.

            // Type '2' in 'txtCameraSelfie' text box
            uITxtCameraSelfieEdit.Text = this.RecordedMethod1Params.UITxtCameraSelfieEditText;

            // Click 'NumericUpDown' text box
            Mouse.Click(uINumericUpDownEdit, new Point(204, 15));

            // Type '1' in 'NumericUpDown' text box
            Keyboard.SendKeys(uINumericUpDownEdit, this.RecordedMethod1Params.UINumericUpDownEditSendKeys, ModifierKeys.None);

            // Click 'CPU:' text box
            Mouse.Click(uICPUEdit, new Point(205, 7));

            // Type '1' in 'CPU:' text box
            Keyboard.SendKeys(uICPUEdit, this.RecordedMethod1Params.UICPUEditSendKeys, ModifierKeys.None);

            // Type '1' in 'txtCPU' text box
            uITxtCPUEdit.Text = this.RecordedMethod1Params.UITxtCPUEditText;

            // Type '1' in 'txtGPU' text box
            uITxtGPUEdit.Text = this.RecordedMethod1Params.UITxtGPUEditText;

            // Type '1' in 'txtBatteries' text box
            uITxtBatteriesEdit.Text = this.RecordedMethod1Params.UITxtBatteriesEditText;

            // Type '1' in 'txtSim' text box
            uITxtSimEdit.Text = this.RecordedMethod1Params.UITxtSimEditText;

            // Type '1' in 'txtOparatingSystem' text box
            uITxtOparatingSystemEdit.Text = this.RecordedMethod1Params.UITxtOparatingSystemEditText;

            // Click 'Hoàn tất' button
            Mouse.Click(uIHoàntấtButton, new Point(1, 1));

            // Click 'Thêm mới' button
            Mouse.Click(uIThêmmớiButton, new Point(1, 1));

            // Click '&OK' button
            Mouse.Click(uIOKButton, new Point(1, 1));
        }
        
        /// <summary>
        /// RecordedMethod2 - Use 'RecordedMethod2Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            DXButton uIThêmsảnphẩmButton = this.UISảnphẩmWindow.UIThêmsảnphẩmButton;
            WinEdit uITxtProductNameEdit = this.UIThôngtinsảnphẩmWindow.UITxtProductNameWindow.UITxtProductNameEdit;
            WinEdit uITxtMadeInEdit = this.UIThôngtinsảnphẩmWindow.UITxtMadeInWindow.UITxtMadeInEdit;
            WinEdit uITxtUnitPriceImportEdit = this.UIThôngtinsảnphẩmWindow.UITxtUnitPriceImportWindow.UITxtUnitPriceImportEdit;
            DXButton uIBtnChoseImagesButton = this.UIThôngtinsảnphẩmWindow.UIBtnChoseImagesButton;
            WinListItem uIIphone12promaxxamnewListItem = this.UIOpenWindow.UIItemWindow.UIItemsViewList.UIIphone12promaxxamnewListItem;
            DXButton uIBtnChoseListImagesButton = this.UIThôngtinsảnphẩmWindow.UIBtnChoseListImagesButton;
            WinEdit uITxtProductDetailsEdit = this.UIThôngtinsảnphẩmWindow.UITxtProductDetailsWindow.UITxtProductDetailsEdit;
            WinEdit uITxtScreenEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtScreenWindow.UITxtScreenEdit;
            WinEdit uITxtRearCameraEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtRearCameraWindow.UITxtRearCameraEdit;
            WinEdit uITxtCameraSelfieEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtCameraSelfieWindow.UITxtCameraSelfieEdit;
            WinEdit uINumericUpDownEdit = this.UIThôngtinmôtảchitiếtsWindow.UINumericUpDownSpinner.UINumericUpDownEdit;
            WinEdit uICPUEdit = this.UIThôngtinmôtảchitiếtsWindow.UICPUSpinner.UICPUEdit;
            WinEdit uITxtCPUEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtCPUWindow.UITxtCPUEdit;
            WinEdit uITxtGPUEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtGPUWindow.UITxtGPUEdit;
            WinEdit uITxtBatteriesEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtBatteriesWindow.UITxtBatteriesEdit;
            WinEdit uITxtSimEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtSimWindow.UITxtSimEdit;
            WinEdit uITxtOparatingSystemEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtOparatingSystemWindow.UITxtOparatingSystemEdit;
            DXButton uIHoàntấtButton = this.UIThôngtinmôtảchitiếtsWindow.UIHoàntấtButton;
            DXButton uIThêmmớiButton = this.UIThôngtinsảnphẩmWindow.UIThêmmớiButton;
            DXButton uIOKButton = this.UIItemWindow.UIThôngbáoWindow.UIOKButton;
            #endregion

            // Click 'Thêm sản phẩm' button
            Mouse.Click(uIThêmsảnphẩmButton, new Point(1, 1));

            // Type 'a' in 'txtProductName' text box
            uITxtProductNameEdit.Text = this.RecordedMethod2Params.UITxtProductNameEditText;

            // Type 'a' in 'txtMadeIn' text box
            uITxtMadeInEdit.Text = this.RecordedMethod2Params.UITxtMadeInEditText;

            // Last mouse action was not recorded.

            // Type '21' in 'txtUnitPriceImport' text box
            uITxtUnitPriceImportEdit.Text = this.RecordedMethod2Params.UITxtUnitPriceImportEditText;

            // Click 'btnChoseImages' button
            Mouse.Click(uIBtnChoseImagesButton, new Point(1, 1));

            // Double-Click 'iphone-12-pro-max-xam-new-600x600-200x200.jpg' list item
            Mouse.DoubleClick(uIIphone12promaxxamnewListItem, new Point(75, 104));

            // Click 'btnChoseListImages' button
            Mouse.Click(uIBtnChoseListImagesButton, new Point(1, 1));

            // Double-Click 'iphone-12-pro-max-xam-new-600x600-200x200.jpg' list item
            Mouse.DoubleClick(uIIphone12promaxxamnewListItem, new Point(86, 109));

            // Click 'txtProductDetails' text box
            Mouse.Click(uITxtProductDetailsEdit, new Point(324, 23));

            // Type 'a' in 'txtScreen' text box
            uITxtScreenEdit.Text = this.RecordedMethod2Params.UITxtScreenEditText;

            // Type 'a' in 'txtRearCamera' text box
            uITxtRearCameraEdit.Text = this.RecordedMethod2Params.UITxtRearCameraEditText;

            // Type 'a' in 'txtCameraSelfie' text box
            uITxtCameraSelfieEdit.Text = this.RecordedMethod2Params.UITxtCameraSelfieEditText;

            // Click 'NumericUpDown' text box
            Mouse.Click(uINumericUpDownEdit, new Point(206, 11));

            // Type '2' in 'NumericUpDown' text box
            Keyboard.SendKeys(uINumericUpDownEdit, this.RecordedMethod2Params.UINumericUpDownEditSendKeys, ModifierKeys.None);

            // Click 'CPU:' text box
            Mouse.Click(uICPUEdit, new Point(206, 6));

            // Type '2' in 'CPU:' text box
            Keyboard.SendKeys(uICPUEdit, this.RecordedMethod2Params.UICPUEditSendKeys, ModifierKeys.None);

            // Type 'a' in 'txtCPU' text box
            uITxtCPUEdit.Text = this.RecordedMethod2Params.UITxtCPUEditText;

            // Type 'a' in 'txtGPU' text box
            uITxtGPUEdit.Text = this.RecordedMethod2Params.UITxtGPUEditText;

            // Type 'a' in 'txtBatteries' text box
            uITxtBatteriesEdit.Text = this.RecordedMethod2Params.UITxtBatteriesEditText;

            // Type 'a' in 'txtSim' text box
            uITxtSimEdit.Text = this.RecordedMethod2Params.UITxtSimEditText;

            // Type 'a' in 'txtOparatingSystem' text box
            uITxtOparatingSystemEdit.Text = this.RecordedMethod2Params.UITxtOparatingSystemEditText;

            // Click 'Hoàn tất' button
            Mouse.Click(uIHoàntấtButton, new Point(1, 1));

            // Click 'Thêm mới' button
            Mouse.Click(uIThêmmớiButton, new Point(1, 1));

            // Click '&OK' button
            Mouse.Click(uIOKButton, new Point(1, 1));
        }
        
        /// <summary>
        /// RecordedMethod3 - Use 'RecordedMethod3Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod3()
        {
            #region Variable Declarations
            DXButton uIThêmsảnphẩmButton = this.UISảnphẩmWindow.UIThêmsảnphẩmButton;
            WinEdit uITxtProductNameEdit = this.UIThôngtinsảnphẩmWindow.UITxtProductNameWindow.UITxtProductNameEdit;
            WinEdit uITxtMadeInEdit = this.UIThôngtinsảnphẩmWindow.UITxtMadeInWindow.UITxtMadeInEdit;
            WinEdit uITxtUnitPriceImportEdit = this.UIThôngtinsảnphẩmWindow.UITxtUnitPriceImportWindow.UITxtUnitPriceImportEdit;
            DXButton uIBtnChoseImagesButton = this.UIThôngtinsảnphẩmWindow.UIBtnChoseImagesButton;
            WinListItem uIIphone12promaxxamnewListItem = this.UIOpenWindow.UIItemWindow.UIItemsViewList.UIIphone12promaxxamnewListItem;
            DXButton uIBtnChoseListImagesButton = this.UIThôngtinsảnphẩmWindow.UIBtnChoseListImagesButton;
            WinEdit uITxtProductDetailsEdit = this.UIThôngtinsảnphẩmWindow.UITxtProductDetailsWindow.UITxtProductDetailsEdit;
            WinEdit uITxtOparatingSystemEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtOparatingSystemWindow.UITxtOparatingSystemEdit;
            WinEdit uITxtScreenEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtScreenWindow.UITxtScreenEdit;
            WinEdit uITxtRearCameraEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtRearCameraWindow.UITxtRearCameraEdit;
            WinEdit uITxtCameraSelfieEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtCameraSelfieWindow.UITxtCameraSelfieEdit;
            WinEdit uINumericUpDownEdit = this.UIThôngtinmôtảchitiếtsWindow.UINumericUpDownSpinner.UINumericUpDownEdit;
            WinEdit uICPUEdit = this.UIThôngtinmôtảchitiếtsWindow.UICPUSpinner.UICPUEdit;
            WinEdit uITxtCPUEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtCPUWindow.UITxtCPUEdit;
            WinEdit uITxtGPUEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtGPUWindow.UITxtGPUEdit;
            WinEdit uITxtBatteriesEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtBatteriesWindow.UITxtBatteriesEdit;
            WinEdit uITxtSimEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtSimWindow.UITxtSimEdit;
            DXButton uIHoàntấtButton = this.UIThôngtinmôtảchitiếtsWindow.UIHoàntấtButton;
            DXButton uIOKButton = this.UIItemWindow.UIThôngbáoWindow.UIOKButton;
            #endregion

            // Click 'Thêm sản phẩm' button
            Mouse.Click(uIThêmsảnphẩmButton, new Point(1, 1));

            // Click 'Thêm sản phẩm' button
            Mouse.Click(uIThêmsảnphẩmButton, new Point(1, 1));

            // Type 'tr' in 'txtProductName' text box
            uITxtProductNameEdit.Text = this.RecordedMethod3Params.UITxtProductNameEditText;

            // Type 'tr' in 'txtMadeIn' text box
            uITxtMadeInEdit.Text = this.RecordedMethod3Params.UITxtMadeInEditText;

            // Type '12' in 'txtUnitPriceImport' text box
            uITxtUnitPriceImportEdit.Text = this.RecordedMethod3Params.UITxtUnitPriceImportEditText;

            // Click 'btnChoseImages' button
            Mouse.Click(uIBtnChoseImagesButton, new Point(1, 1));

            // Double-Click 'iphone-12-pro-max-xam-new-600x600-200x200.jpg' list item
            Mouse.DoubleClick(uIIphone12promaxxamnewListItem, new Point(92, 64));

            // Click 'btnChoseListImages' button
            Mouse.Click(uIBtnChoseListImagesButton, new Point(1, 1));

            // Double-Click 'iphone-12-pro-max-xam-new-600x600-200x200.jpg' list item
            Mouse.DoubleClick(uIIphone12promaxxamnewListItem, new Point(95, 92));

            // Click 'txtProductDetails' text box
            Mouse.Click(uITxtProductDetailsEdit, new Point(289, 44));

            // Click 'txtOparatingSystem' text box
            Mouse.Click(uITxtOparatingSystemEdit, new Point(141, 13));

            // Type '' in 'txtScreen' text box
            uITxtScreenEdit.Text = this.RecordedMethod3Params.UITxtScreenEditText;

            // Type '1' in 'txtRearCamera' text box
            uITxtRearCameraEdit.Text = this.RecordedMethod3Params.UITxtRearCameraEditText;

            // Type '1' in 'txtCameraSelfie' text box
            uITxtCameraSelfieEdit.Text = this.RecordedMethod3Params.UITxtCameraSelfieEditText;

            // Click 'NumericUpDown' text box
            Mouse.Click(uINumericUpDownEdit, new Point(205, 16));

            // Type '6' in 'NumericUpDown' text box
            Keyboard.SendKeys(uINumericUpDownEdit, this.RecordedMethod3Params.UINumericUpDownEditSendKeys, ModifierKeys.None);

            // Click 'CPU:' text box
            Mouse.Click(uICPUEdit, new Point(206, 8));

            // Type '128' in 'CPU:' text box
            Keyboard.SendKeys(uICPUEdit, this.RecordedMethod3Params.UICPUEditSendKeys, ModifierKeys.None);

            // Type '2' in 'txtCPU' text box
            uITxtCPUEdit.Text = this.RecordedMethod3Params.UITxtCPUEditText;

            // Type '3' in 'txtGPU' text box
            uITxtGPUEdit.Text = this.RecordedMethod3Params.UITxtGPUEditText;

            // Type '4' in 'txtBatteries' text box
            uITxtBatteriesEdit.Text = this.RecordedMethod3Params.UITxtBatteriesEditText;

            // Type '5' in 'txtSim' text box
            uITxtSimEdit.Text = this.RecordedMethod3Params.UITxtSimEditText;

            // Type '6' in 'txtOparatingSystem' text box
            uITxtOparatingSystemEdit.Text = this.RecordedMethod3Params.UITxtOparatingSystemEditText;

            // Click 'Hoàn tất' button
            Mouse.Click(uIHoàntấtButton, new Point(1, 1));

            // Click '&OK' button
            Mouse.Click(uIOKButton, new Point(1, 1));
        }
        
        /// <summary>
        /// RecordedMethod4 - Use 'RecordedMethod4Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod4()
        {
            #region Variable Declarations
            DXButton uIThêmsảnphẩmButton = this.UISảnphẩmWindow.UIThêmsảnphẩmButton;
            WinEdit uITxtProductNameEdit = this.UIThôngtinsảnphẩmWindow.UITxtProductNameWindow.UITxtProductNameEdit;
            WinEdit uITxtMadeInEdit = this.UIThôngtinsảnphẩmWindow.UITxtMadeInWindow.UITxtMadeInEdit;
            WinEdit uITxtUnitPriceImportEdit = this.UIThôngtinsảnphẩmWindow.UITxtUnitPriceImportWindow.UITxtUnitPriceImportEdit;
            DXButton uIBtnChoseImagesButton = this.UIThôngtinsảnphẩmWindow.UIBtnChoseImagesButton;
            WinListItem uIIphone12promaxxamnewListItem = this.UIOpenWindow.UIItemWindow.UIItemsViewList.UIIphone12promaxxamnewListItem;
            DXButton uIBtnChoseListImagesButton = this.UIThôngtinsảnphẩmWindow.UIBtnChoseListImagesButton;
            WinEdit uITxtProductDetailsEdit = this.UIThôngtinsảnphẩmWindow.UITxtProductDetailsWindow.UITxtProductDetailsEdit;
            WinEdit uITxtOparatingSystemEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtOparatingSystemWindow.UITxtOparatingSystemEdit;
            WinEdit uITxtScreenEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtScreenWindow.UITxtScreenEdit;
            WinEdit uITxtRearCameraEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtRearCameraWindow.UITxtRearCameraEdit;
            WinEdit uITxtCameraSelfieEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtCameraSelfieWindow.UITxtCameraSelfieEdit;
            WinEdit uINumericUpDownEdit = this.UIThôngtinmôtảchitiếtsWindow.UINumericUpDownSpinner.UINumericUpDownEdit;
            WinEdit uICPUEdit = this.UIThôngtinmôtảchitiếtsWindow.UICPUSpinner.UICPUEdit;
            WinButton uIDownButton = this.UIThôngtinmôtảchitiếtsWindow.UISpinnerSpinner.UIDownButton;
            WinEdit uITxtCPUEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtCPUWindow.UITxtCPUEdit;
            WinGroup uIThôngtinmôtảsảnphẩmGroup = this.UIThôngtinmôtảchitiếtsWindow.UIThôngtinmôtảsảnphẩmWindow.UIThôngtinmôtảsảnphẩmGroup;
            WinEdit uITxtGPUEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtGPUWindow.UITxtGPUEdit;
            WinEdit uITxtBatteriesEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtBatteriesWindow.UITxtBatteriesEdit;
            WinEdit uITxtSimEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtSimWindow.UITxtSimEdit;
            DXButton uIHoàntấtButton = this.UIThôngtinmôtảchitiếtsWindow.UIHoàntấtButton;
            DXButton uIOKButton = this.UIItemWindow.UIThôngbáoWindow.UIOKButton;
            #endregion

            // Click 'Thêm sản phẩm' button
            Mouse.Click(uIThêmsảnphẩmButton, new Point(1, 1));

            // Type 'ip' in 'txtProductName' text box
            uITxtProductNameEdit.Text = this.RecordedMethod4Params.UITxtProductNameEditText;

            // Type 'trung' in 'txtMadeIn' text box
            uITxtMadeInEdit.Text = this.RecordedMethod4Params.UITxtMadeInEditText;

            // Type '24' in 'txtUnitPriceImport' text box
            uITxtUnitPriceImportEdit.Text = this.RecordedMethod4Params.UITxtUnitPriceImportEditText;

            // Click 'btnChoseImages' button
            Mouse.Click(uIBtnChoseImagesButton, new Point(1, 1));

            // Double-Click 'iphone-12-pro-max-xam-new-600x600-200x200.jpg' list item
            Mouse.DoubleClick(uIIphone12promaxxamnewListItem, new Point(14, 80));

            // Click 'btnChoseListImages' button
            Mouse.Click(uIBtnChoseListImagesButton, new Point(1, 1));

            // Double-Click 'iphone-12-pro-max-xam-new-600x600-200x200.jpg' list item
            Mouse.DoubleClick(uIIphone12promaxxamnewListItem, new Point(61, 99));

            // Click 'txtProductDetails' text box
            Mouse.Click(uITxtProductDetailsEdit, new Point(361, 49));

            // Click 'txtOparatingSystem' text box
            Mouse.Click(uITxtOparatingSystemEdit, new Point(213, 18));

            // Type '' in 'txtScreen' text box
            uITxtScreenEdit.Text = this.RecordedMethod4Params.UITxtScreenEditText;

            // Type '1' in 'txtRearCamera' text box
            uITxtRearCameraEdit.Text = this.RecordedMethod4Params.UITxtRearCameraEditText;

            // Type '1' in 'txtCameraSelfie' text box
            uITxtCameraSelfieEdit.Text = this.RecordedMethod4Params.UITxtCameraSelfieEditText;

            // Click 'NumericUpDown' text box
            Mouse.Click(uINumericUpDownEdit, new Point(205, 15));

            // Type '6' in 'NumericUpDown' text box
            Keyboard.SendKeys(uINumericUpDownEdit, this.RecordedMethod4Params.UINumericUpDownEditSendKeys, ModifierKeys.None);

            // Click 'CPU:' text box
            Mouse.Click(uICPUEdit, new Point(203, 17));

            // Click 'Down' button
            Mouse.Click(uIDownButton, new Point(2, 7));

            // Click 'CPU:' text box
            Mouse.Click(uICPUEdit, new Point(207, 6));

            // Type '128' in 'CPU:' text box
            Keyboard.SendKeys(uICPUEdit, this.RecordedMethod4Params.UICPUEditSendKeys, ModifierKeys.None);

            // Type '12' in 'txtCPU' text box
            uITxtCPUEdit.Text = this.RecordedMethod4Params.UITxtCPUEditText;

            // Click 'Thông tin mô tả sản phẩm' group
            Mouse.Click(uIThôngtinmôtảsảnphẩmGroup, new Point(312, 233));

            // Type '1' in 'txtGPU' text box
            uITxtGPUEdit.Text = this.RecordedMethod4Params.UITxtGPUEditText;

            // Type '2' in 'txtBatteries' text box
            uITxtBatteriesEdit.Text = this.RecordedMethod4Params.UITxtBatteriesEditText;

            // Type '1' in 'txtSim' text box
            uITxtSimEdit.Text = this.RecordedMethod4Params.UITxtSimEditText;

            // Type '1' in 'txtOparatingSystem' text box
            uITxtOparatingSystemEdit.Text = this.RecordedMethod4Params.UITxtOparatingSystemEditText;

            // Click 'Hoàn tất' button
            Mouse.Click(uIHoàntấtButton, new Point(1, 1));

            // Click '&OK' button
            Mouse.Click(uIOKButton, new Point(1, 1));
        }
        
        /// <summary>
        /// RecordedMethod5 - Use 'RecordedMethod5Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod5()
        {
            #region Variable Declarations
            DXButton uIThêmsảnphẩmButton = this.UISảnphẩmWindow.UIThêmsảnphẩmButton;
            WinEdit uITxtProductNameEdit = this.UIThôngtinsảnphẩmWindow.UITxtProductNameWindow.UITxtProductNameEdit;
            WinEdit uITxtMadeInEdit = this.UIThôngtinsảnphẩmWindow.UITxtMadeInWindow.UITxtMadeInEdit;
            WinEdit uITxtUnitPriceImportEdit = this.UIThôngtinsảnphẩmWindow.UITxtUnitPriceImportWindow.UITxtUnitPriceImportEdit;
            DXButton uIBtnChoseListImagesButton = this.UIThôngtinsảnphẩmWindow.UIBtnChoseListImagesButton;
            WinListItem uIIphone12promaxxamnewListItem = this.UIOpenWindow.UIItemWindow.UIItemsViewList.UIIphone12promaxxamnewListItem;
            WinEdit uITxtProductDetailsEdit = this.UIThôngtinsảnphẩmWindow.UITxtProductDetailsWindow.UITxtProductDetailsEdit;
            WinEdit uITxtOparatingSystemEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtOparatingSystemWindow.UITxtOparatingSystemEdit;
            WinEdit uITxtScreenEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtScreenWindow.UITxtScreenEdit;
            WinEdit uITxtRearCameraEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtRearCameraWindow.UITxtRearCameraEdit;
            WinEdit uITxtCameraSelfieEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtCameraSelfieWindow.UITxtCameraSelfieEdit;
            WinEdit uINumericUpDownEdit = this.UIThôngtinmôtảchitiếtsWindow.UINumericUpDownSpinner.UINumericUpDownEdit;
            WinEdit uICPUEdit = this.UIThôngtinmôtảchitiếtsWindow.UICPUSpinner.UICPUEdit;
            WinEdit uITxtCPUEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtCPUWindow.UITxtCPUEdit;
            WinEdit uITxtGPUEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtGPUWindow.UITxtGPUEdit;
            WinEdit uITxtBatteriesEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtBatteriesWindow.UITxtBatteriesEdit;
            WinEdit uITxtSimEdit = this.UIThôngtinmôtảchitiếtsWindow.UITxtSimWindow.UITxtSimEdit;
            DXButton uIHoàntấtButton = this.UIThôngtinmôtảchitiếtsWindow.UIHoàntấtButton;
            DXButton uIThêmmớiButton = this.UIThôngtinsảnphẩmWindow.UIThêmmớiButton;
            DXButton uIOKButton = this.UIItemWindow.UIThôngbáoWindow.UIOKButton;
            #endregion

            // Click 'Thêm sản phẩm' button
            Mouse.Click(uIThêmsảnphẩmButton, new Point(1, 1));

            // Type 'tr' in 'txtProductName' text box
            uITxtProductNameEdit.Text = this.RecordedMethod5Params.UITxtProductNameEditText;

            // Last mouse action was not recorded.

            // Type 'trt' in 'txtProductName' text box
            uITxtProductNameEdit.Text = this.RecordedMethod5Params.UITxtProductNameEditText1;

            // Last mouse action was not recorded.

            // Type 'r' in 'txtMadeIn' text box
            uITxtMadeInEdit.Text = this.RecordedMethod5Params.UITxtMadeInEditText;

            // Type '12' in 'txtUnitPriceImport' text box
            uITxtUnitPriceImportEdit.Text = this.RecordedMethod5Params.UITxtUnitPriceImportEditText;

            // Click 'btnChoseListImages' button
            Mouse.Click(uIBtnChoseListImagesButton, new Point(1, 1));

            // Double-Click 'iphone-12-pro-max-xam-new-600x600-200x200.jpg' list item
            Mouse.DoubleClick(uIIphone12promaxxamnewListItem, new Point(94, 79));

            // Click 'txtProductDetails' text box
            Mouse.Click(uITxtProductDetailsEdit, new Point(246, 38));

            // Move 'txtOparatingSystem' text box
            Mouse.StartDragging(uITxtOparatingSystemEdit, new Point(98, -29));
            Mouse.StopDragging(uITxtOparatingSystemEdit, 0, 36);

            // Type '1' in 'txtScreen' text box
            uITxtScreenEdit.Text = this.RecordedMethod5Params.UITxtScreenEditText;

            // Last mouse action was not recorded.

            // Type '12' in 'txtScreen' text box
            uITxtScreenEdit.Text = this.RecordedMethod5Params.UITxtScreenEditText1;

            // Last mouse action was not recorded.

            // Click 'txtRearCamera' text box
            Mouse.Click(uITxtRearCameraEdit, new Point(55, 15));

            // Click 'txtCameraSelfie' text box
            Mouse.Click(uITxtCameraSelfieEdit, new Point(55, 12));

            // Type '2' in 'txtRearCamera' text box
            uITxtRearCameraEdit.Text = this.RecordedMethod5Params.UITxtRearCameraEditText;

            // Type '1' in 'txtCameraSelfie' text box
            uITxtCameraSelfieEdit.Text = this.RecordedMethod5Params.UITxtCameraSelfieEditText;

            // Click 'NumericUpDown' text box
            Mouse.Click(uINumericUpDownEdit, new Point(205, 7));

            // Type '1' in 'NumericUpDown' text box
            Keyboard.SendKeys(uINumericUpDownEdit, this.RecordedMethod5Params.UINumericUpDownEditSendKeys, ModifierKeys.None);

            // Click 'CPU:' text box
            Mouse.Click(uICPUEdit, new Point(205, 11));

            // Type '2' in 'CPU:' text box
            Keyboard.SendKeys(uICPUEdit, this.RecordedMethod5Params.UICPUEditSendKeys, ModifierKeys.None);

            // Type '1' in 'txtCPU' text box
            uITxtCPUEdit.Text = this.RecordedMethod5Params.UITxtCPUEditText;

            // Type '1' in 'txtGPU' text box
            uITxtGPUEdit.Text = this.RecordedMethod5Params.UITxtGPUEditText;

            // Type '1' in 'txtBatteries' text box
            uITxtBatteriesEdit.Text = this.RecordedMethod5Params.UITxtBatteriesEditText;

            // Type '1' in 'txtSim' text box
            uITxtSimEdit.Text = this.RecordedMethod5Params.UITxtSimEditText;

            // Type '1' in 'txtOparatingSystem' text box
            uITxtOparatingSystemEdit.Text = this.RecordedMethod5Params.UITxtOparatingSystemEditText;

            // Click 'Hoàn tất' button
            Mouse.Click(uIHoàntấtButton, new Point(1, 1));

            // Click 'Thêm mới' button
            Mouse.Click(uIThêmmớiButton, new Point(1, 1));

            // Click '&OK' button
            Mouse.Click(uIOKButton, new Point(1, 1));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public virtual RecordedMethod2Params RecordedMethod2Params
        {
            get
            {
                if ((this.mRecordedMethod2Params == null))
                {
                    this.mRecordedMethod2Params = new RecordedMethod2Params();
                }
                return this.mRecordedMethod2Params;
            }
        }
        
        public virtual RecordedMethod3Params RecordedMethod3Params
        {
            get
            {
                if ((this.mRecordedMethod3Params == null))
                {
                    this.mRecordedMethod3Params = new RecordedMethod3Params();
                }
                return this.mRecordedMethod3Params;
            }
        }
        
        public virtual RecordedMethod4Params RecordedMethod4Params
        {
            get
            {
                if ((this.mRecordedMethod4Params == null))
                {
                    this.mRecordedMethod4Params = new RecordedMethod4Params();
                }
                return this.mRecordedMethod4Params;
            }
        }
        
        public virtual RecordedMethod5Params RecordedMethod5Params
        {
            get
            {
                if ((this.mRecordedMethod5Params == null))
                {
                    this.mRecordedMethod5Params = new RecordedMethod5Params();
                }
                return this.mRecordedMethod5Params;
            }
        }
        
        public UISảnphẩmWindow UISảnphẩmWindow
        {
            get
            {
                if ((this.mUISảnphẩmWindow == null))
                {
                    this.mUISảnphẩmWindow = new UISảnphẩmWindow();
                }
                return this.mUISảnphẩmWindow;
            }
        }
        
        public UIThôngtinsảnphẩmWindow UIThôngtinsảnphẩmWindow
        {
            get
            {
                if ((this.mUIThôngtinsảnphẩmWindow == null))
                {
                    this.mUIThôngtinsảnphẩmWindow = new UIThôngtinsảnphẩmWindow();
                }
                return this.mUIThôngtinsảnphẩmWindow;
            }
        }
        
        public UIOpenWindow UIOpenWindow
        {
            get
            {
                if ((this.mUIOpenWindow == null))
                {
                    this.mUIOpenWindow = new UIOpenWindow();
                }
                return this.mUIOpenWindow;
            }
        }
        
        public UIThôngtinmôtảchitiếtsWindow UIThôngtinmôtảchitiếtsWindow
        {
            get
            {
                if ((this.mUIThôngtinmôtảchitiếtsWindow == null))
                {
                    this.mUIThôngtinmôtảchitiếtsWindow = new UIThôngtinmôtảchitiếtsWindow();
                }
                return this.mUIThôngtinmôtảchitiếtsWindow;
            }
        }
        
        public UIItemWindow1 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow1();
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private RecordedMethod2Params mRecordedMethod2Params;
        
        private RecordedMethod3Params mRecordedMethod3Params;
        
        private RecordedMethod4Params mRecordedMethod4Params;
        
        private RecordedMethod5Params mRecordedMethod5Params;
        
        private UISảnphẩmWindow mUISảnphẩmWindow;
        
        private UIThôngtinsảnphẩmWindow mUIThôngtinsảnphẩmWindow;
        
        private UIOpenWindow mUIOpenWindow;
        
        private UIThôngtinmôtảchitiếtsWindow mUIThôngtinmôtảchitiếtsWindow;
        
        private UIItemWindow1 mUIItemWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'a' in 'txtProductName' text box
        /// </summary>
        public string UITxtProductNameEditText = "a";
        
        /// <summary>
        /// Type 'a' in 'txtMadeIn' text box
        /// </summary>
        public string UITxtMadeInEditText = "a";
        
        /// <summary>
        /// Type '12' in 'txtUnitPriceImport' text box
        /// </summary>
        public string UITxtUnitPriceImportEditText = "12";
        
        /// <summary>
        /// Type 'a' in 'txtScreen' text box
        /// </summary>
        public string UITxtScreenEditText = "a";
        
        /// <summary>
        /// Type '2' in 'txtRearCamera' text box
        /// </summary>
        public string UITxtRearCameraEditText = "2";
        
        /// <summary>
        /// Type '2' in 'txtCameraSelfie' text box
        /// </summary>
        public string UITxtCameraSelfieEditText = "2";
        
        /// <summary>
        /// Type '1' in 'NumericUpDown' text box
        /// </summary>
        public string UINumericUpDownEditSendKeys = "1";
        
        /// <summary>
        /// Type '1' in 'CPU:' text box
        /// </summary>
        public string UICPUEditSendKeys = "1";
        
        /// <summary>
        /// Type '1' in 'txtCPU' text box
        /// </summary>
        public string UITxtCPUEditText = "1";
        
        /// <summary>
        /// Type '1' in 'txtGPU' text box
        /// </summary>
        public string UITxtGPUEditText = "1";
        
        /// <summary>
        /// Type '1' in 'txtBatteries' text box
        /// </summary>
        public string UITxtBatteriesEditText = "1";
        
        /// <summary>
        /// Type '1' in 'txtSim' text box
        /// </summary>
        public string UITxtSimEditText = "1";
        
        /// <summary>
        /// Type '1' in 'txtOparatingSystem' text box
        /// </summary>
        public string UITxtOparatingSystemEditText = "1";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class RecordedMethod2Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'a' in 'txtProductName' text box
        /// </summary>
        public string UITxtProductNameEditText = "a";
        
        /// <summary>
        /// Type 'a' in 'txtMadeIn' text box
        /// </summary>
        public string UITxtMadeInEditText = "a";
        
        /// <summary>
        /// Type '21' in 'txtUnitPriceImport' text box
        /// </summary>
        public string UITxtUnitPriceImportEditText = "21";
        
        /// <summary>
        /// Type 'a' in 'txtScreen' text box
        /// </summary>
        public string UITxtScreenEditText = "a";
        
        /// <summary>
        /// Type 'a' in 'txtRearCamera' text box
        /// </summary>
        public string UITxtRearCameraEditText = "a";
        
        /// <summary>
        /// Type 'a' in 'txtCameraSelfie' text box
        /// </summary>
        public string UITxtCameraSelfieEditText = "a";
        
        /// <summary>
        /// Type '2' in 'NumericUpDown' text box
        /// </summary>
        public string UINumericUpDownEditSendKeys = "2";
        
        /// <summary>
        /// Type '2' in 'CPU:' text box
        /// </summary>
        public string UICPUEditSendKeys = "2";
        
        /// <summary>
        /// Type 'a' in 'txtCPU' text box
        /// </summary>
        public string UITxtCPUEditText = "a";
        
        /// <summary>
        /// Type 'a' in 'txtGPU' text box
        /// </summary>
        public string UITxtGPUEditText = "a";
        
        /// <summary>
        /// Type 'a' in 'txtBatteries' text box
        /// </summary>
        public string UITxtBatteriesEditText = "a";
        
        /// <summary>
        /// Type 'a' in 'txtSim' text box
        /// </summary>
        public string UITxtSimEditText = "a";
        
        /// <summary>
        /// Type 'a' in 'txtOparatingSystem' text box
        /// </summary>
        public string UITxtOparatingSystemEditText = "a";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod3'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class RecordedMethod3Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'tr' in 'txtProductName' text box
        /// </summary>
        public string UITxtProductNameEditText = "tr";
        
        /// <summary>
        /// Type 'tr' in 'txtMadeIn' text box
        /// </summary>
        public string UITxtMadeInEditText = "tr";
        
        /// <summary>
        /// Type '12' in 'txtUnitPriceImport' text box
        /// </summary>
        public string UITxtUnitPriceImportEditText = "12";
        
        /// <summary>
        /// Type '' in 'txtScreen' text box
        /// </summary>
        public string UITxtScreenEditText = "";
        
        /// <summary>
        /// Type '1' in 'txtRearCamera' text box
        /// </summary>
        public string UITxtRearCameraEditText = "1";
        
        /// <summary>
        /// Type '1' in 'txtCameraSelfie' text box
        /// </summary>
        public string UITxtCameraSelfieEditText = "1";
        
        /// <summary>
        /// Type '6' in 'NumericUpDown' text box
        /// </summary>
        public string UINumericUpDownEditSendKeys = "6";
        
        /// <summary>
        /// Type '128' in 'CPU:' text box
        /// </summary>
        public string UICPUEditSendKeys = "128";
        
        /// <summary>
        /// Type '2' in 'txtCPU' text box
        /// </summary>
        public string UITxtCPUEditText = "2";
        
        /// <summary>
        /// Type '3' in 'txtGPU' text box
        /// </summary>
        public string UITxtGPUEditText = "3";
        
        /// <summary>
        /// Type '4' in 'txtBatteries' text box
        /// </summary>
        public string UITxtBatteriesEditText = "4";
        
        /// <summary>
        /// Type '5' in 'txtSim' text box
        /// </summary>
        public string UITxtSimEditText = "5";
        
        /// <summary>
        /// Type '6' in 'txtOparatingSystem' text box
        /// </summary>
        public string UITxtOparatingSystemEditText = "6";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod4'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class RecordedMethod4Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'ip' in 'txtProductName' text box
        /// </summary>
        public string UITxtProductNameEditText = "ip";
        
        /// <summary>
        /// Type 'trung' in 'txtMadeIn' text box
        /// </summary>
        public string UITxtMadeInEditText = "trung";
        
        /// <summary>
        /// Type '24' in 'txtUnitPriceImport' text box
        /// </summary>
        public string UITxtUnitPriceImportEditText = "24";
        
        /// <summary>
        /// Type '' in 'txtScreen' text box
        /// </summary>
        public string UITxtScreenEditText = "";
        
        /// <summary>
        /// Type '1' in 'txtRearCamera' text box
        /// </summary>
        public string UITxtRearCameraEditText = "1";
        
        /// <summary>
        /// Type '1' in 'txtCameraSelfie' text box
        /// </summary>
        public string UITxtCameraSelfieEditText = "1";
        
        /// <summary>
        /// Type '6' in 'NumericUpDown' text box
        /// </summary>
        public string UINumericUpDownEditSendKeys = "6";
        
        /// <summary>
        /// Type '128' in 'CPU:' text box
        /// </summary>
        public string UICPUEditSendKeys = "128";
        
        /// <summary>
        /// Type '12' in 'txtCPU' text box
        /// </summary>
        public string UITxtCPUEditText = "12";
        
        /// <summary>
        /// Type '1' in 'txtGPU' text box
        /// </summary>
        public string UITxtGPUEditText = "1";
        
        /// <summary>
        /// Type '2' in 'txtBatteries' text box
        /// </summary>
        public string UITxtBatteriesEditText = "2";
        
        /// <summary>
        /// Type '1' in 'txtSim' text box
        /// </summary>
        public string UITxtSimEditText = "1";
        
        /// <summary>
        /// Type '1' in 'txtOparatingSystem' text box
        /// </summary>
        public string UITxtOparatingSystemEditText = "1";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod5'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class RecordedMethod5Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'tr' in 'txtProductName' text box
        /// </summary>
        public string UITxtProductNameEditText = "tr";
        
        /// <summary>
        /// Type 'trt' in 'txtProductName' text box
        /// </summary>
        public string UITxtProductNameEditText1 = "trt";
        
        /// <summary>
        /// Type 'r' in 'txtMadeIn' text box
        /// </summary>
        public string UITxtMadeInEditText = "r";
        
        /// <summary>
        /// Type '12' in 'txtUnitPriceImport' text box
        /// </summary>
        public string UITxtUnitPriceImportEditText = "12";
        
        /// <summary>
        /// Type '1' in 'txtScreen' text box
        /// </summary>
        public string UITxtScreenEditText = "1";
        
        /// <summary>
        /// Type '12' in 'txtScreen' text box
        /// </summary>
        public string UITxtScreenEditText1 = "12";
        
        /// <summary>
        /// Type '2' in 'txtRearCamera' text box
        /// </summary>
        public string UITxtRearCameraEditText = "2";
        
        /// <summary>
        /// Type '1' in 'txtCameraSelfie' text box
        /// </summary>
        public string UITxtCameraSelfieEditText = "1";
        
        /// <summary>
        /// Type '1' in 'NumericUpDown' text box
        /// </summary>
        public string UINumericUpDownEditSendKeys = "1";
        
        /// <summary>
        /// Type '2' in 'CPU:' text box
        /// </summary>
        public string UICPUEditSendKeys = "2";
        
        /// <summary>
        /// Type '1' in 'txtCPU' text box
        /// </summary>
        public string UITxtCPUEditText = "1";
        
        /// <summary>
        /// Type '1' in 'txtGPU' text box
        /// </summary>
        public string UITxtGPUEditText = "1";
        
        /// <summary>
        /// Type '1' in 'txtBatteries' text box
        /// </summary>
        public string UITxtBatteriesEditText = "1";
        
        /// <summary>
        /// Type '1' in 'txtSim' text box
        /// </summary>
        public string UITxtSimEditText = "1";
        
        /// <summary>
        /// Type '1' in 'txtOparatingSystem' text box
        /// </summary>
        public string UITxtOparatingSystemEditText = "1";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UISảnphẩmWindow : WinWindow
    {
        
        public UISảnphẩmWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Sản phẩm";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Sản phẩm");
            #endregion
        }
        
        #region Properties
        public DXButton UIThêmsảnphẩmButton
        {
            get
            {
                if ((this.mUIThêmsảnphẩmButton == null))
                {
                    this.mUIThêmsảnphẩmButton = new DXButton(this);
                    #region Search Criteria
                    this.mUIThêmsảnphẩmButton.SearchProperties[DXTestControl.PropertyNames.Name] = "btnInsertProduct";
                    this.mUIThêmsảnphẩmButton.SearchProperties[DXTestControl.PropertyNames.ClassName] = "ButtonDesign";
                    this.mUIThêmsảnphẩmButton.SearchProperties[DXTestControl.PropertyNames.HierarchyLevel] = "3";
                    this.mUIThêmsảnphẩmButton.WindowTitles.Add("Sản phẩm");
                    #endregion
                }
                return this.mUIThêmsảnphẩmButton;
            }
        }
        #endregion
        
        #region Fields
        private DXButton mUIThêmsảnphẩmButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIThôngtinsảnphẩmWindow : WinWindow
    {
        
        public UIThôngtinsảnphẩmWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Thông tin sản phẩm";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public UITxtProductNameWindow UITxtProductNameWindow
        {
            get
            {
                if ((this.mUITxtProductNameWindow == null))
                {
                    this.mUITxtProductNameWindow = new UITxtProductNameWindow(this);
                }
                return this.mUITxtProductNameWindow;
            }
        }
        
        public UITxtMadeInWindow UITxtMadeInWindow
        {
            get
            {
                if ((this.mUITxtMadeInWindow == null))
                {
                    this.mUITxtMadeInWindow = new UITxtMadeInWindow(this);
                }
                return this.mUITxtMadeInWindow;
            }
        }
        
        public UITxtUnitPriceImportWindow UITxtUnitPriceImportWindow
        {
            get
            {
                if ((this.mUITxtUnitPriceImportWindow == null))
                {
                    this.mUITxtUnitPriceImportWindow = new UITxtUnitPriceImportWindow(this);
                }
                return this.mUITxtUnitPriceImportWindow;
            }
        }
        
        public DXButton UIBtnChoseImagesButton
        {
            get
            {
                if ((this.mUIBtnChoseImagesButton == null))
                {
                    this.mUIBtnChoseImagesButton = new DXButton(this);
                    #region Search Criteria
                    this.mUIBtnChoseImagesButton.SearchProperties[DXTestControl.PropertyNames.Name] = "btnChoseImages";
                    this.mUIBtnChoseImagesButton.SearchProperties[DXTestControl.PropertyNames.ClassName] = "SimpleButton";
                    this.mUIBtnChoseImagesButton.SearchProperties[DXTestControl.PropertyNames.HierarchyLevel] = "2";
                    this.mUIBtnChoseImagesButton.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUIBtnChoseImagesButton;
            }
        }
        
        public UIThôngtinsảnphẩmGroup UIThôngtinsảnphẩmGroup
        {
            get
            {
                if ((this.mUIThôngtinsảnphẩmGroup == null))
                {
                    this.mUIThôngtinsảnphẩmGroup = new UIThôngtinsảnphẩmGroup(this);
                }
                return this.mUIThôngtinsảnphẩmGroup;
            }
        }
        
        public DXButton UIBtnChoseListImagesButton
        {
            get
            {
                if ((this.mUIBtnChoseListImagesButton == null))
                {
                    this.mUIBtnChoseListImagesButton = new DXButton(this);
                    #region Search Criteria
                    this.mUIBtnChoseListImagesButton.SearchProperties[DXTestControl.PropertyNames.Name] = "btnChoseListImages";
                    this.mUIBtnChoseListImagesButton.SearchProperties[DXTestControl.PropertyNames.ClassName] = "SimpleButton";
                    this.mUIBtnChoseListImagesButton.SearchProperties[DXTestControl.PropertyNames.HierarchyLevel] = "2";
                    this.mUIBtnChoseListImagesButton.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUIBtnChoseListImagesButton;
            }
        }
        
        public UITxtProductDetailsWindow UITxtProductDetailsWindow
        {
            get
            {
                if ((this.mUITxtProductDetailsWindow == null))
                {
                    this.mUITxtProductDetailsWindow = new UITxtProductDetailsWindow(this);
                }
                return this.mUITxtProductDetailsWindow;
            }
        }
        
        public DXButton UIThêmmớiButton
        {
            get
            {
                if ((this.mUIThêmmớiButton == null))
                {
                    this.mUIThêmmớiButton = new DXButton(this);
                    #region Search Criteria
                    this.mUIThêmmớiButton.SearchProperties[DXTestControl.PropertyNames.Name] = "btnAddNew";
                    this.mUIThêmmớiButton.SearchProperties[DXTestControl.PropertyNames.ClassName] = "ButtonDesign";
                    this.mUIThêmmớiButton.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUIThêmmớiButton;
            }
        }
        #endregion
        
        #region Fields
        private UITxtProductNameWindow mUITxtProductNameWindow;
        
        private UITxtMadeInWindow mUITxtMadeInWindow;
        
        private UITxtUnitPriceImportWindow mUITxtUnitPriceImportWindow;
        
        private DXButton mUIBtnChoseImagesButton;
        
        private UIThôngtinsảnphẩmGroup mUIThôngtinsảnphẩmGroup;
        
        private DXButton mUIBtnChoseListImagesButton;
        
        private UITxtProductDetailsWindow mUITxtProductDetailsWindow;
        
        private DXButton mUIThêmmớiButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtProductNameWindow : WinWindow
    {
        
        public UITxtProductNameWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtProductName";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtProductNameEdit
        {
            get
            {
                if ((this.mUITxtProductNameEdit == null))
                {
                    this.mUITxtProductNameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtProductNameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Nhóm sản phẩm:";
                    this.mUITxtProductNameEdit.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtProductNameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtProductNameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtMadeInWindow : WinWindow
    {
        
        public UITxtMadeInWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtMadeIn";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtMadeInEdit
        {
            get
            {
                if ((this.mUITxtMadeInEdit == null))
                {
                    this.mUITxtMadeInEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtMadeInEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Tên sản phẩm:";
                    this.mUITxtMadeInEdit.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtMadeInEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtMadeInEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtUnitPriceImportWindow : WinWindow
    {
        
        public UITxtUnitPriceImportWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtUnitPriceImport";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtUnitPriceImportEdit
        {
            get
            {
                if ((this.mUITxtUnitPriceImportEdit == null))
                {
                    this.mUITxtUnitPriceImportEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtUnitPriceImportEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Giảm giá:";
                    this.mUITxtUnitPriceImportEdit.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtUnitPriceImportEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtUnitPriceImportEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIThôngtinsảnphẩmGroup : WinGroup
    {
        
        public UIThôngtinsảnphẩmGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Thông tin sản phẩm";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinWindow UIBtnChoseListImagesWindow
        {
            get
            {
                if ((this.mUIBtnChoseListImagesWindow == null))
                {
                    this.mUIBtnChoseListImagesWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIBtnChoseListImagesWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
                    this.mUIBtnChoseListImagesWindow.SearchProperties[WinWindow.PropertyNames.Instance] = "5";
                    this.mUIBtnChoseListImagesWindow.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUIBtnChoseListImagesWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIBtnChoseListImagesWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtProductDetailsWindow : WinWindow
    {
        
        public UITxtProductDetailsWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtProductDetails";
            this.WindowTitles.Add("Thông tin sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtProductDetailsEdit
        {
            get
            {
                if ((this.mUITxtProductDetailsEdit == null))
                {
                    this.mUITxtProductDetailsEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtProductDetailsEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Hình minh họa:";
                    this.mUITxtProductDetailsEdit.WindowTitles.Add("Thông tin sản phẩm");
                    #endregion
                }
                return this.mUITxtProductDetailsEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtProductDetailsEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIOpenWindow : WinWindow
    {
        
        public UIOpenWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Open";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Open");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Items View";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("Open");
            #endregion
        }
        
        #region Properties
        public UIItemsViewList UIItemsViewList
        {
            get
            {
                if ((this.mUIItemsViewList == null))
                {
                    this.mUIItemsViewList = new UIItemsViewList(this);
                }
                return this.mUIItemsViewList;
            }
        }
        #endregion
        
        #region Fields
        private UIItemsViewList mUIItemsViewList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIItemsViewList : WinList
    {
        
        public UIItemsViewList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinList.PropertyNames.Name] = "Items View";
            this.WindowTitles.Add("Open");
            #endregion
        }
        
        #region Properties
        public WinListItem UIIphone12promaxxamnewListItem
        {
            get
            {
                if ((this.mUIIphone12promaxxamnewListItem == null))
                {
                    this.mUIIphone12promaxxamnewListItem = new WinListItem(this);
                    #region Search Criteria
                    this.mUIIphone12promaxxamnewListItem.SearchProperties[WinListItem.PropertyNames.Name] = "iphone-12-pro-max-xam-new-600x600-200x200.jpg";
                    this.mUIIphone12promaxxamnewListItem.WindowTitles.Add("Open");
                    #endregion
                }
                return this.mUIIphone12promaxxamnewListItem;
            }
        }
        #endregion
        
        #region Fields
        private WinListItem mUIIphone12promaxxamnewListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIThôngtinmôtảchitiếtsWindow : WinWindow
    {
        
        public UIThôngtinmôtảchitiếtsWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Thông tin mô tả chi tiết sản phẩm";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public UITxtScreenWindow UITxtScreenWindow
        {
            get
            {
                if ((this.mUITxtScreenWindow == null))
                {
                    this.mUITxtScreenWindow = new UITxtScreenWindow(this);
                }
                return this.mUITxtScreenWindow;
            }
        }
        
        public UITxtRearCameraWindow UITxtRearCameraWindow
        {
            get
            {
                if ((this.mUITxtRearCameraWindow == null))
                {
                    this.mUITxtRearCameraWindow = new UITxtRearCameraWindow(this);
                }
                return this.mUITxtRearCameraWindow;
            }
        }
        
        public UITxtCameraSelfieWindow UITxtCameraSelfieWindow
        {
            get
            {
                if ((this.mUITxtCameraSelfieWindow == null))
                {
                    this.mUITxtCameraSelfieWindow = new UITxtCameraSelfieWindow(this);
                }
                return this.mUITxtCameraSelfieWindow;
            }
        }
        
        public UINumericUpDownSpinner UINumericUpDownSpinner
        {
            get
            {
                if ((this.mUINumericUpDownSpinner == null))
                {
                    this.mUINumericUpDownSpinner = new UINumericUpDownSpinner(this);
                }
                return this.mUINumericUpDownSpinner;
            }
        }
        
        public UICPUSpinner UICPUSpinner
        {
            get
            {
                if ((this.mUICPUSpinner == null))
                {
                    this.mUICPUSpinner = new UICPUSpinner(this);
                }
                return this.mUICPUSpinner;
            }
        }
        
        public UITxtCPUWindow UITxtCPUWindow
        {
            get
            {
                if ((this.mUITxtCPUWindow == null))
                {
                    this.mUITxtCPUWindow = new UITxtCPUWindow(this);
                }
                return this.mUITxtCPUWindow;
            }
        }
        
        public UITxtGPUWindow UITxtGPUWindow
        {
            get
            {
                if ((this.mUITxtGPUWindow == null))
                {
                    this.mUITxtGPUWindow = new UITxtGPUWindow(this);
                }
                return this.mUITxtGPUWindow;
            }
        }
        
        public UITxtBatteriesWindow UITxtBatteriesWindow
        {
            get
            {
                if ((this.mUITxtBatteriesWindow == null))
                {
                    this.mUITxtBatteriesWindow = new UITxtBatteriesWindow(this);
                }
                return this.mUITxtBatteriesWindow;
            }
        }
        
        public UITxtSimWindow UITxtSimWindow
        {
            get
            {
                if ((this.mUITxtSimWindow == null))
                {
                    this.mUITxtSimWindow = new UITxtSimWindow(this);
                }
                return this.mUITxtSimWindow;
            }
        }
        
        public UITxtOparatingSystemWindow UITxtOparatingSystemWindow
        {
            get
            {
                if ((this.mUITxtOparatingSystemWindow == null))
                {
                    this.mUITxtOparatingSystemWindow = new UITxtOparatingSystemWindow(this);
                }
                return this.mUITxtOparatingSystemWindow;
            }
        }
        
        public DXButton UIHoàntấtButton
        {
            get
            {
                if ((this.mUIHoàntấtButton == null))
                {
                    this.mUIHoàntấtButton = new DXButton(this);
                    #region Search Criteria
                    this.mUIHoàntấtButton.SearchProperties[DXTestControl.PropertyNames.Name] = "btnCompleted";
                    this.mUIHoàntấtButton.SearchProperties[DXTestControl.PropertyNames.ClassName] = "ButtonDesign";
                    this.mUIHoàntấtButton.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUIHoàntấtButton;
            }
        }
        
        public UISpinnerSpinner UISpinnerSpinner
        {
            get
            {
                if ((this.mUISpinnerSpinner == null))
                {
                    this.mUISpinnerSpinner = new UISpinnerSpinner(this);
                }
                return this.mUISpinnerSpinner;
            }
        }
        
        public UIThôngtinmôtảsảnphẩmWindow UIThôngtinmôtảsảnphẩmWindow
        {
            get
            {
                if ((this.mUIThôngtinmôtảsảnphẩmWindow == null))
                {
                    this.mUIThôngtinmôtảsảnphẩmWindow = new UIThôngtinmôtảsảnphẩmWindow(this);
                }
                return this.mUIThôngtinmôtảsảnphẩmWindow;
            }
        }
        #endregion
        
        #region Fields
        private UITxtScreenWindow mUITxtScreenWindow;
        
        private UITxtRearCameraWindow mUITxtRearCameraWindow;
        
        private UITxtCameraSelfieWindow mUITxtCameraSelfieWindow;
        
        private UINumericUpDownSpinner mUINumericUpDownSpinner;
        
        private UICPUSpinner mUICPUSpinner;
        
        private UITxtCPUWindow mUITxtCPUWindow;
        
        private UITxtGPUWindow mUITxtGPUWindow;
        
        private UITxtBatteriesWindow mUITxtBatteriesWindow;
        
        private UITxtSimWindow mUITxtSimWindow;
        
        private UITxtOparatingSystemWindow mUITxtOparatingSystemWindow;
        
        private DXButton mUIHoàntấtButton;
        
        private UISpinnerSpinner mUISpinnerSpinner;
        
        private UIThôngtinmôtảsảnphẩmWindow mUIThôngtinmôtảsảnphẩmWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtScreenWindow : WinWindow
    {
        
        public UITxtScreenWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtScreen";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtScreenEdit
        {
            get
            {
                if ((this.mUITxtScreenEdit == null))
                {
                    this.mUITxtScreenEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtScreenEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Camera sau:";
                    this.mUITxtScreenEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtScreenEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtScreenEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtRearCameraWindow : WinWindow
    {
        
        public UITxtRearCameraWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtRearCamera";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtRearCameraEdit
        {
            get
            {
                if ((this.mUITxtRearCameraEdit == null))
                {
                    this.mUITxtRearCameraEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtRearCameraEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Màn hình:";
                    this.mUITxtRearCameraEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtRearCameraEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtRearCameraEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtCameraSelfieWindow : WinWindow
    {
        
        public UITxtCameraSelfieWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtCameraSelfie";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtCameraSelfieEdit
        {
            get
            {
                if ((this.mUITxtCameraSelfieEdit == null))
                {
                    this.mUITxtCameraSelfieEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtCameraSelfieEdit.SearchProperties[WinEdit.PropertyNames.Name] = "GB";
                    this.mUITxtCameraSelfieEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtCameraSelfieEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtCameraSelfieEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UINumericUpDownSpinner : WinSpinner
    {
        
        public UINumericUpDownSpinner(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinSpinner.PropertyNames.Name] = "NumericUpDown";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UINumericUpDownEdit
        {
            get
            {
                if ((this.mUINumericUpDownEdit == null))
                {
                    this.mUINumericUpDownEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUINumericUpDownEdit.SearchProperties[WinEdit.PropertyNames.Name] = "NumericUpDown";
                    this.mUINumericUpDownEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUINumericUpDownEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINumericUpDownEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UICPUSpinner : WinSpinner
    {
        
        public UICPUSpinner(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinSpinner.PropertyNames.Name] = "CPU:";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UICPUEdit
        {
            get
            {
                if ((this.mUICPUEdit == null))
                {
                    this.mUICPUEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICPUEdit.SearchProperties[WinEdit.PropertyNames.Name] = "CPU:";
                    this.mUICPUEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUICPUEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICPUEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtCPUWindow : WinWindow
    {
        
        public UITxtCPUWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtCPU";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtCPUEdit
        {
            get
            {
                if ((this.mUITxtCPUEdit == null))
                {
                    this.mUITxtCPUEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtCPUEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtCPUEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtCPUEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtGPUWindow : WinWindow
    {
        
        public UITxtGPUWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtGPU";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtGPUEdit
        {
            get
            {
                if ((this.mUITxtGPUEdit == null))
                {
                    this.mUITxtGPUEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtGPUEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtGPUEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtGPUEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtBatteriesWindow : WinWindow
    {
        
        public UITxtBatteriesWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtBatteries";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtBatteriesEdit
        {
            get
            {
                if ((this.mUITxtBatteriesEdit == null))
                {
                    this.mUITxtBatteriesEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtBatteriesEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtBatteriesEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtBatteriesEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtSimWindow : WinWindow
    {
        
        public UITxtSimWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtSim";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtSimEdit
        {
            get
            {
                if ((this.mUITxtSimEdit == null))
                {
                    this.mUITxtSimEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtSimEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtSimEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtSimEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UITxtOparatingSystemWindow : WinWindow
    {
        
        public UITxtOparatingSystemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtOparatingSystem";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtOparatingSystemEdit
        {
            get
            {
                if ((this.mUITxtOparatingSystemEdit == null))
                {
                    this.mUITxtOparatingSystemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtOparatingSystemEdit.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUITxtOparatingSystemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtOparatingSystemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UISpinnerSpinner : WinSpinner
    {
        
        public UISpinnerSpinner(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinSpinner.PropertyNames.Name] = "Spinner";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinButton UIDownButton
        {
            get
            {
                if ((this.mUIDownButton == null))
                {
                    this.mUIDownButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIDownButton.SearchProperties[WinButton.PropertyNames.Name] = "Down";
                    this.mUIDownButton.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUIDownButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIDownButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIThôngtinmôtảsảnphẩmWindow : WinWindow
    {
        
        public UIThôngtinmôtảsảnphẩmWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "groupBox1";
            this.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
            #endregion
        }
        
        #region Properties
        public WinGroup UIThôngtinmôtảsảnphẩmGroup
        {
            get
            {
                if ((this.mUIThôngtinmôtảsảnphẩmGroup == null))
                {
                    this.mUIThôngtinmôtảsảnphẩmGroup = new WinGroup(this);
                    #region Search Criteria
                    this.mUIThôngtinmôtảsảnphẩmGroup.SearchProperties[WinControl.PropertyNames.Name] = "Thông tin mô tả sản phẩm";
                    this.mUIThôngtinmôtảsảnphẩmGroup.WindowTitles.Add("Thông tin mô tả chi tiết sản phẩm");
                    #endregion
                }
                return this.mUIThôngtinmôtảsảnphẩmGroup;
            }
        }
        #endregion
        
        #region Fields
        private WinGroup mUIThôngtinmôtảsảnphẩmGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Desktop 1";
            #endregion
        }
        
        #region Properties
        public UIThôngbáoWindow UIThôngbáoWindow
        {
            get
            {
                if ((this.mUIThôngbáoWindow == null))
                {
                    this.mUIThôngbáoWindow = new UIThôngbáoWindow(this);
                }
                return this.mUIThôngbáoWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIThôngbáoWindow mUIThôngbáoWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.31306.167")]
    public class UIThôngbáoWindow : DXWindow
    {
        
        public UIThôngbáoWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = "Thông báo";
            this.SearchProperties[DXTestControl.PropertyNames.ClassName] = "XtraMessageBoxForm";
            #endregion
        }
        
        #region Properties
        public DXButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new DXButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[DXTestControl.PropertyNames.Name] = "Thông báoSimpleButton[0]";
                    this.mUIOKButton.SearchProperties[DXTestControl.PropertyNames.ClassName] = "SimpleButton";
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private DXButton mUIOKButton;
        #endregion
    }
}
